// @generated by lean/Emit.lean. DO NOT EDIT.
//! Verified `triple_des_cbc` functions for `arm`.
#![allow(dead_code)]

/// Triple DES-CBC encryption (NIST SP 800-38A §6.2, FIPS 46-3) of whole blocks, in place: replaces the `n` 8-byte blocks `P₁ … Pₙ` at `data` with `Cⱼ = CIPH_K(Pⱼ ⊕ Cⱼ₋₁)`, where `C₀` is the block at `*iv`, which is only read: a further call continues the message from `Cₙ`, the last block at `data` on return. `CIPH_K` is Triple DES encryption under the schedule written by `vg_triple_des_expand_key`. No padding is added.
///
/// Contract: `VG.Spec.TripleDes.cbcEncryptContract`. Constant time: only the pointers and `n` may affect timing, not the schedule, the chaining value or the data.
///
/// Baseline ARMv7: the generic CBC encryption of `Impl/Modes/Arm/`, one block at a time (CBC encryption is sequential), calling the verified `vg_triple_des_ecb_encrypt` on each block in a 56-byte working space on the stack, zeroed on return.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 384 bytes.
/// * `iv` must be valid for reads of 8 bytes.
/// * `data` must be valid for reads and writes of `8 * n` bytes.
/// * `data` must not overlap `schedule` or `iv` (distinct Rust objects never do).
/// * None of `schedule`, `iv` and `data` may overlap the 1088 bytes of stack below the stack pointer, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_triple_des_cbc_encrypt(schedule: *const [u8; 384], iv: *const [u8; 8], data: *mut [u8; 8], n: usize) {
    core::arch::naked_asm!(
        "sub sp, sp, #64",
        "add r12, sp, #0",
        "str lr, [r12, #4]",
        "add lr, sp, #8",
        "str lr, [r12, #0]",
        "ldr lr, [sp, #4]",
        "ldr r12, [sp, #0]",
        "str r4, [r12, #0]",
        "str r5, [r12, #4]",
        "str r6, [r12, #8]",
        "str r7, [r12, #12]",
        "str r9, [r12, #20]",
        "str r10, [r12, #24]",
        "str r11, [r12, #28]",
        "str lr, [r12, #32]",
        "str r8, [r12, #16]",
        "mov r4, r0",
        "mov r5, r1",
        "mov r6, r2",
        "mov r7, r3",
        "mov r8, r12",
        "ldr r9, [r5, #0]",
        "str r9, [r8, #40]",
        "ldr r9, [r5, #4]",
        "str r9, [r8, #44]",
        "cmp r7, #0",
        "beq 20f",
        "22:",
        "ldr r9, [r8, #40]",
        "ldr r10, [r6, #0]",
        "eor r9, r9, r10",
        "str r9, [r8, #40]",
        "ldr r9, [r8, #44]",
        "ldr r10, [r6, #4]",
        "eor r9, r9, r10",
        "str r9, [r8, #44]",
        "mov r0, r4",
        "add r1, r8, #40",
        "mov r2, #1",
        "bl {vg_triple_des_ecb_encrypt}",
        "ldr r9, [r8, #40]",
        "str r9, [r6, #0]",
        "ldr r9, [r8, #44]",
        "str r9, [r6, #4]",
        "add r6, r6, #8",
        "subs r7, r7, #1",
        "bne 22b",
        "b 21f",
        "20:",
        "21:",
        "ldr r4, [r8, #0]",
        "ldr r5, [r8, #4]",
        "ldr r6, [r8, #8]",
        "ldr r7, [r8, #12]",
        "ldr r9, [r8, #20]",
        "ldr r10, [r8, #24]",
        "ldr r11, [r8, #28]",
        "ldr lr, [r8, #32]",
        "ldr r8, [r8, #16]",
        "add r12, sp, #8",
        "mov r2, #0",
        "str r2, [r12, #0]",
        "str r2, [r12, #4]",
        "str r2, [r12, #8]",
        "str r2, [r12, #12]",
        "str r2, [r12, #16]",
        "str r2, [r12, #20]",
        "str r2, [r12, #24]",
        "str r2, [r12, #28]",
        "str r2, [r12, #32]",
        "str r2, [r12, #36]",
        "str r2, [r12, #40]",
        "str r2, [r12, #44]",
        "str r2, [r12, #48]",
        "str r2, [r12, #52]",
        "add sp, sp, #64",
        "bx lr",
        vg_triple_des_ecb_encrypt = sym super::triple_des::vg_triple_des_ecb_encrypt,
    )
}

/// Triple DES-CBC decryption (NIST SP 800-38A §6.2, FIPS 46-3) of whole blocks, in place: replaces the `n` 8-byte blocks `C₁ … Cₙ` at `data` with `Pⱼ = CIPH⁻¹_K(Cⱼ) ⊕ Cⱼ₋₁`, where `C₀` is the block at `*iv`, which is only read: a further call continues the message from `Cₙ`, the last block at `data` on entry. `CIPH⁻¹_K` is Triple DES decryption under the schedule written by `vg_triple_des_expand_key`. No padding is removed.
///
/// Contract: `VG.Spec.TripleDes.cbcDecryptContract`. Constant time: only the pointers and `n` may affect timing, not the schedule, the chaining value or the data.
///
/// Baseline ARMv7: the generic CBC decryption of `Impl/Modes/Arm/`, one block at a time, calling the verified `vg_triple_des_ecb_decrypt` on each block in place, with the chaining value in a 56-byte working space on the stack, zeroed on return.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 384 bytes.
/// * `iv` must be valid for reads of 8 bytes.
/// * `data` must be valid for reads and writes of `8 * n` bytes.
/// * `data` must not overlap `schedule` or `iv` (distinct Rust objects never do).
/// * None of `schedule`, `iv` and `data` may overlap the 1088 bytes of stack below the stack pointer, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_triple_des_cbc_decrypt(schedule: *const [u8; 384], iv: *const [u8; 8], data: *mut [u8; 8], n: usize) {
    core::arch::naked_asm!(
        "sub sp, sp, #64",
        "add r12, sp, #0",
        "str lr, [r12, #4]",
        "add lr, sp, #8",
        "str lr, [r12, #0]",
        "ldr lr, [sp, #4]",
        "ldr r12, [sp, #0]",
        "str r4, [r12, #0]",
        "str r5, [r12, #4]",
        "str r6, [r12, #8]",
        "str r7, [r12, #12]",
        "str r9, [r12, #20]",
        "str r10, [r12, #24]",
        "str r11, [r12, #28]",
        "str lr, [r12, #32]",
        "str r8, [r12, #16]",
        "mov r4, r0",
        "mov r5, r1",
        "mov r6, r2",
        "mov r7, r3",
        "mov r8, r12",
        "ldr r9, [r5, #0]",
        "str r9, [r8, #40]",
        "ldr r9, [r5, #4]",
        "str r9, [r8, #44]",
        "cmp r7, #0",
        "beq 20f",
        "22:",
        "ldr r9, [r6, #0]",
        "str r9, [r8, #48]",
        "ldr r9, [r6, #4]",
        "str r9, [r8, #52]",
        "mov r0, r4",
        "add r1, r6, #0",
        "mov r2, #1",
        "bl {vg_triple_des_ecb_decrypt}",
        "ldr r9, [r6, #0]",
        "ldr r10, [r8, #40]",
        "eor r9, r9, r10",
        "str r9, [r6, #0]",
        "ldr r9, [r6, #4]",
        "ldr r10, [r8, #44]",
        "eor r9, r9, r10",
        "str r9, [r6, #4]",
        "ldr r9, [r8, #48]",
        "str r9, [r8, #40]",
        "ldr r9, [r8, #52]",
        "str r9, [r8, #44]",
        "add r6, r6, #8",
        "subs r7, r7, #1",
        "bne 22b",
        "b 21f",
        "20:",
        "21:",
        "ldr r4, [r8, #0]",
        "ldr r5, [r8, #4]",
        "ldr r6, [r8, #8]",
        "ldr r7, [r8, #12]",
        "ldr r9, [r8, #20]",
        "ldr r10, [r8, #24]",
        "ldr r11, [r8, #28]",
        "ldr lr, [r8, #32]",
        "ldr r8, [r8, #16]",
        "add r12, sp, #8",
        "mov r2, #0",
        "str r2, [r12, #0]",
        "str r2, [r12, #4]",
        "str r2, [r12, #8]",
        "str r2, [r12, #12]",
        "str r2, [r12, #16]",
        "str r2, [r12, #20]",
        "str r2, [r12, #24]",
        "str r2, [r12, #28]",
        "str r2, [r12, #32]",
        "str r2, [r12, #36]",
        "str r2, [r12, #40]",
        "str r2, [r12, #44]",
        "str r2, [r12, #48]",
        "str r2, [r12, #52]",
        "add sp, sp, #64",
        "bx lr",
        vg_triple_des_ecb_decrypt = sym super::triple_des::vg_triple_des_ecb_decrypt,
    )
}
