// @generated by lean/Emit.lean. DO NOT EDIT.
//! Verified `aes_xts` functions for `x86`.
#![allow(dead_code)]

/// The CPU features `vg_aes_xts_encrypt_aesni` requires (`Artifact.features`).
pub(crate) const VG_AES_XTS_ENCRYPT_AESNI_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["aes"]);

/// XTS-AES encryption (IEEE Std 1619-2007 §5.3.1, NIST SP 800-38E) of whole blocks, in place: replaces the `n` 16-byte blocks `Pⱼ` at `data` with `Cⱼ = AES-enc(Key1, Pⱼ ⊕ Tⱼ) ⊕ Tⱼ`, where `T₀` is the tweak at `*tweak` and `Tⱼ₊₁ = Tⱼ ⊗ α` (§5.2), and `*tweak` with `Tₙ` (leaving it unchanged if `n = 0`), so that a further call continues the data unit. `AES-enc(Key1, ·)` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it. The caller computes the first tweak, `AES-enc(Key2, i)`, and steals ciphertext for a partial last block.
///
/// Contract: `VG.Spec.Xts.aesEncryptContract`. Constant time: only the pointers, `rounds` and `n` may affect timing, not the key schedule, the tweak or the data.
///
/// This implementation enciphers one block at a time with `vg_aes_encrypt_blocks_aesni`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `tweak` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `tweak`, `data` and `scratch` must not overlap each other, `schedule` or the arguments on the stack (distinct Rust objects never do).
/// * None of `schedule`, `tweak`, `data` and `scratch` may overlap the return address on the stack or the 24 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `aes` target feature.
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_aes_xts_encrypt_aesni(schedule: *const [u8; 240], rounds: usize, tweak: *mut [u8; 16], data: *mut [u8; 16], n: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+24]",
        "mov DWORD PTR [eax+2064], ebx",
        "mov DWORD PTR [eax+2068], esi",
        "mov DWORD PTR [eax+2072], edi",
        "mov DWORD PTR [eax+2076], ebp",
        "mov esi, DWORD PTR [esp+16]",
        "mov eax, DWORD PTR [esp+20]",
        "test eax, eax",
        "je 20f",
        "22:",
        "mov ebx, DWORD PTR [esp+12]",
        "mov eax, DWORD PTR [esi]",
        "mov ecx, DWORD PTR [ebx]",
        "xor eax, ecx",
        "mov DWORD PTR [esi], eax",
        "mov eax, DWORD PTR [esi+4]",
        "mov ecx, DWORD PTR [ebx+4]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+4], eax",
        "mov eax, DWORD PTR [esi+8]",
        "mov ecx, DWORD PTR [ebx+8]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+8], eax",
        "mov eax, DWORD PTR [esi+12]",
        "mov ecx, DWORD PTR [ebx+12]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+12], eax",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov ebx, esi",
        "mov edi, 1",
        "mov ebp, DWORD PTR [esp+24]",
        "push ebp",
        "push edi",
        "push ebx",
        "push ecx",
        "push eax",
        "call {vg_aes_encrypt_blocks_aesni}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ebx, DWORD PTR [esp+12]",
        "mov eax, DWORD PTR [esi]",
        "mov ecx, DWORD PTR [ebx]",
        "xor eax, ecx",
        "mov DWORD PTR [esi], eax",
        "mov eax, DWORD PTR [esi+4]",
        "mov ecx, DWORD PTR [ebx+4]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+4], eax",
        "mov eax, DWORD PTR [esi+8]",
        "mov ecx, DWORD PTR [ebx+8]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+8], eax",
        "mov eax, DWORD PTR [esi+12]",
        "mov ecx, DWORD PTR [ebx+12]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+12], eax",
        "mov eax, DWORD PTR [ebx]",
        "mov ecx, DWORD PTR [ebx+4]",
        "mov edx, DWORD PTR [ebx+8]",
        "mov edi, DWORD PTR [ebx+12]",
        "add eax, eax",
        "adc ecx, ecx",
        "adc edx, edx",
        "adc edi, edi",
        "sbb ebp, ebp",
        "and ebp, 135",
        "xor eax, ebp",
        "mov DWORD PTR [ebx], eax",
        "mov DWORD PTR [ebx+4], ecx",
        "mov DWORD PTR [ebx+8], edx",
        "mov DWORD PTR [ebx+12], edi",
        "add esi, 16",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, eax",
        "add eax, eax",
        "add eax, eax",
        "add eax, eax",
        "add eax, DWORD PTR [esp+16]",
        "cmp esi, eax",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov eax, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [eax+2064]",
        "mov esi, DWORD PTR [eax+2068]",
        "mov edi, DWORD PTR [eax+2072]",
        "mov ebp, DWORD PTR [eax+2076]",
        "ret",
        ".p2align 6",
        vg_aes_encrypt_blocks_aesni = sym super::aes::vg_aes_encrypt_blocks_aesni,
    )
}

/// The CPU features `vg_aes_xts_decrypt_aesni` requires (`Artifact.features`).
pub(crate) const VG_AES_XTS_DECRYPT_AESNI_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["aes"]);

/// XTS-AES decryption (IEEE Std 1619-2007 §5.4.1, NIST SP 800-38E) of whole blocks, in place: replaces the `n` 16-byte blocks `Cⱼ` at `data` with `Pⱼ = AES-dec(Key1, Cⱼ ⊕ Tⱼ) ⊕ Tⱼ`, where `T₀` is the tweak at `*tweak` and `Tⱼ₊₁ = Tⱼ ⊗ α` (§5.2), and `*tweak` with `Tₙ` (leaving it unchanged if `n = 0`), so that a further call continues the data unit. `AES-dec(Key1, ·)` is the AES inverse cipher (FIPS 197 §5.3) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it. The caller computes the first tweak, `AES-enc(Key2, i)`, and steals ciphertext for a partial last block.
///
/// Contract: `VG.Spec.Xts.aesDecryptContract`. Constant time: only the pointers, `rounds` and `n` may affect timing, not the key schedule, the tweak or the data.
///
/// This implementation deciphers one block at a time with `vg_aes_decrypt_blocks_aesni`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `tweak` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `tweak`, `data` and `scratch` must not overlap each other, `schedule` or the arguments on the stack (distinct Rust objects never do).
/// * None of `schedule`, `tweak`, `data` and `scratch` may overlap the return address on the stack or the 24 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `aes` target feature.
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_aes_xts_decrypt_aesni(schedule: *const [u8; 240], rounds: usize, tweak: *mut [u8; 16], data: *mut [u8; 16], n: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+24]",
        "mov DWORD PTR [eax+2064], ebx",
        "mov DWORD PTR [eax+2068], esi",
        "mov DWORD PTR [eax+2072], edi",
        "mov DWORD PTR [eax+2076], ebp",
        "mov esi, DWORD PTR [esp+16]",
        "mov eax, DWORD PTR [esp+20]",
        "test eax, eax",
        "je 20f",
        "22:",
        "mov ebx, DWORD PTR [esp+12]",
        "mov eax, DWORD PTR [esi]",
        "mov ecx, DWORD PTR [ebx]",
        "xor eax, ecx",
        "mov DWORD PTR [esi], eax",
        "mov eax, DWORD PTR [esi+4]",
        "mov ecx, DWORD PTR [ebx+4]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+4], eax",
        "mov eax, DWORD PTR [esi+8]",
        "mov ecx, DWORD PTR [ebx+8]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+8], eax",
        "mov eax, DWORD PTR [esi+12]",
        "mov ecx, DWORD PTR [ebx+12]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+12], eax",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov ebx, esi",
        "mov edi, 1",
        "mov ebp, DWORD PTR [esp+24]",
        "push ebp",
        "push edi",
        "push ebx",
        "push ecx",
        "push eax",
        "call {vg_aes_decrypt_blocks_aesni}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ebx, DWORD PTR [esp+12]",
        "mov eax, DWORD PTR [esi]",
        "mov ecx, DWORD PTR [ebx]",
        "xor eax, ecx",
        "mov DWORD PTR [esi], eax",
        "mov eax, DWORD PTR [esi+4]",
        "mov ecx, DWORD PTR [ebx+4]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+4], eax",
        "mov eax, DWORD PTR [esi+8]",
        "mov ecx, DWORD PTR [ebx+8]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+8], eax",
        "mov eax, DWORD PTR [esi+12]",
        "mov ecx, DWORD PTR [ebx+12]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+12], eax",
        "mov eax, DWORD PTR [ebx]",
        "mov ecx, DWORD PTR [ebx+4]",
        "mov edx, DWORD PTR [ebx+8]",
        "mov edi, DWORD PTR [ebx+12]",
        "add eax, eax",
        "adc ecx, ecx",
        "adc edx, edx",
        "adc edi, edi",
        "sbb ebp, ebp",
        "and ebp, 135",
        "xor eax, ebp",
        "mov DWORD PTR [ebx], eax",
        "mov DWORD PTR [ebx+4], ecx",
        "mov DWORD PTR [ebx+8], edx",
        "mov DWORD PTR [ebx+12], edi",
        "add esi, 16",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, eax",
        "add eax, eax",
        "add eax, eax",
        "add eax, eax",
        "add eax, DWORD PTR [esp+16]",
        "cmp esi, eax",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov eax, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [eax+2064]",
        "mov esi, DWORD PTR [eax+2068]",
        "mov edi, DWORD PTR [eax+2072]",
        "mov ebp, DWORD PTR [eax+2076]",
        "ret",
        ".p2align 6",
        vg_aes_decrypt_blocks_aesni = sym super::aes::vg_aes_decrypt_blocks_aesni,
    )
}

/// XTS-AES encryption (IEEE Std 1619-2007 §5.3.1, NIST SP 800-38E) of whole blocks, in place: replaces the `n` 16-byte blocks `Pⱼ` at `data` with `Cⱼ = AES-enc(Key1, Pⱼ ⊕ Tⱼ) ⊕ Tⱼ`, where `T₀` is the tweak at `*tweak` and `Tⱼ₊₁ = Tⱼ ⊗ α` (§5.2), and `*tweak` with `Tₙ` (leaving it unchanged if `n = 0`), so that a further call continues the data unit. `AES-enc(Key1, ·)` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it. The caller computes the first tweak, `AES-enc(Key2, i)`, and steals ciphertext for a partial last block.
///
/// Contract: `VG.Spec.Xts.aesEncryptContract`. Constant time: only the pointers, `rounds` and `n` may affect timing, not the key schedule, the tweak or the data.
///
/// This implementation enciphers one block at a time with `vg_aes_encrypt_blocks`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `tweak` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `tweak`, `data` and `scratch` must not overlap each other, `schedule` or the arguments on the stack (distinct Rust objects never do).
/// * None of `schedule`, `tweak`, `data` and `scratch` may overlap the return address on the stack or the 24 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_aes_xts_encrypt(schedule: *const [u8; 240], rounds: usize, tweak: *mut [u8; 16], data: *mut [u8; 16], n: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+24]",
        "mov DWORD PTR [eax+2064], ebx",
        "mov DWORD PTR [eax+2068], esi",
        "mov DWORD PTR [eax+2072], edi",
        "mov DWORD PTR [eax+2076], ebp",
        "mov esi, DWORD PTR [esp+16]",
        "mov eax, DWORD PTR [esp+20]",
        "test eax, eax",
        "je 20f",
        "22:",
        "mov ebx, DWORD PTR [esp+12]",
        "mov eax, DWORD PTR [esi]",
        "mov ecx, DWORD PTR [ebx]",
        "xor eax, ecx",
        "mov DWORD PTR [esi], eax",
        "mov eax, DWORD PTR [esi+4]",
        "mov ecx, DWORD PTR [ebx+4]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+4], eax",
        "mov eax, DWORD PTR [esi+8]",
        "mov ecx, DWORD PTR [ebx+8]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+8], eax",
        "mov eax, DWORD PTR [esi+12]",
        "mov ecx, DWORD PTR [ebx+12]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+12], eax",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov ebx, esi",
        "mov edi, 1",
        "mov ebp, DWORD PTR [esp+24]",
        "push ebp",
        "push edi",
        "push ebx",
        "push ecx",
        "push eax",
        "call {vg_aes_encrypt_blocks}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ebx, DWORD PTR [esp+12]",
        "mov eax, DWORD PTR [esi]",
        "mov ecx, DWORD PTR [ebx]",
        "xor eax, ecx",
        "mov DWORD PTR [esi], eax",
        "mov eax, DWORD PTR [esi+4]",
        "mov ecx, DWORD PTR [ebx+4]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+4], eax",
        "mov eax, DWORD PTR [esi+8]",
        "mov ecx, DWORD PTR [ebx+8]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+8], eax",
        "mov eax, DWORD PTR [esi+12]",
        "mov ecx, DWORD PTR [ebx+12]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+12], eax",
        "mov eax, DWORD PTR [ebx]",
        "mov ecx, DWORD PTR [ebx+4]",
        "mov edx, DWORD PTR [ebx+8]",
        "mov edi, DWORD PTR [ebx+12]",
        "add eax, eax",
        "adc ecx, ecx",
        "adc edx, edx",
        "adc edi, edi",
        "sbb ebp, ebp",
        "and ebp, 135",
        "xor eax, ebp",
        "mov DWORD PTR [ebx], eax",
        "mov DWORD PTR [ebx+4], ecx",
        "mov DWORD PTR [ebx+8], edx",
        "mov DWORD PTR [ebx+12], edi",
        "add esi, 16",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, eax",
        "add eax, eax",
        "add eax, eax",
        "add eax, eax",
        "add eax, DWORD PTR [esp+16]",
        "cmp esi, eax",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov eax, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [eax+2064]",
        "mov esi, DWORD PTR [eax+2068]",
        "mov edi, DWORD PTR [eax+2072]",
        "mov ebp, DWORD PTR [eax+2076]",
        "ret",
        ".p2align 6",
        vg_aes_encrypt_blocks = sym super::aes::vg_aes_encrypt_blocks,
    )
}

/// XTS-AES decryption (IEEE Std 1619-2007 §5.4.1, NIST SP 800-38E) of whole blocks, in place: replaces the `n` 16-byte blocks `Cⱼ` at `data` with `Pⱼ = AES-dec(Key1, Cⱼ ⊕ Tⱼ) ⊕ Tⱼ`, where `T₀` is the tweak at `*tweak` and `Tⱼ₊₁ = Tⱼ ⊗ α` (§5.2), and `*tweak` with `Tₙ` (leaving it unchanged if `n = 0`), so that a further call continues the data unit. `AES-dec(Key1, ·)` is the AES inverse cipher (FIPS 197 §5.3) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it. The caller computes the first tweak, `AES-enc(Key2, i)`, and steals ciphertext for a partial last block.
///
/// Contract: `VG.Spec.Xts.aesDecryptContract`. Constant time: only the pointers, `rounds` and `n` may affect timing, not the key schedule, the tweak or the data.
///
/// This implementation deciphers one block at a time with `vg_aes_decrypt_blocks`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `tweak` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `tweak`, `data` and `scratch` must not overlap each other, `schedule` or the arguments on the stack (distinct Rust objects never do).
/// * None of `schedule`, `tweak`, `data` and `scratch` may overlap the return address on the stack or the 24 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_aes_xts_decrypt(schedule: *const [u8; 240], rounds: usize, tweak: *mut [u8; 16], data: *mut [u8; 16], n: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+24]",
        "mov DWORD PTR [eax+2064], ebx",
        "mov DWORD PTR [eax+2068], esi",
        "mov DWORD PTR [eax+2072], edi",
        "mov DWORD PTR [eax+2076], ebp",
        "mov esi, DWORD PTR [esp+16]",
        "mov eax, DWORD PTR [esp+20]",
        "test eax, eax",
        "je 20f",
        "22:",
        "mov ebx, DWORD PTR [esp+12]",
        "mov eax, DWORD PTR [esi]",
        "mov ecx, DWORD PTR [ebx]",
        "xor eax, ecx",
        "mov DWORD PTR [esi], eax",
        "mov eax, DWORD PTR [esi+4]",
        "mov ecx, DWORD PTR [ebx+4]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+4], eax",
        "mov eax, DWORD PTR [esi+8]",
        "mov ecx, DWORD PTR [ebx+8]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+8], eax",
        "mov eax, DWORD PTR [esi+12]",
        "mov ecx, DWORD PTR [ebx+12]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+12], eax",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov ebx, esi",
        "mov edi, 1",
        "mov ebp, DWORD PTR [esp+24]",
        "push ebp",
        "push edi",
        "push ebx",
        "push ecx",
        "push eax",
        "call {vg_aes_decrypt_blocks}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ebx, DWORD PTR [esp+12]",
        "mov eax, DWORD PTR [esi]",
        "mov ecx, DWORD PTR [ebx]",
        "xor eax, ecx",
        "mov DWORD PTR [esi], eax",
        "mov eax, DWORD PTR [esi+4]",
        "mov ecx, DWORD PTR [ebx+4]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+4], eax",
        "mov eax, DWORD PTR [esi+8]",
        "mov ecx, DWORD PTR [ebx+8]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+8], eax",
        "mov eax, DWORD PTR [esi+12]",
        "mov ecx, DWORD PTR [ebx+12]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+12], eax",
        "mov eax, DWORD PTR [ebx]",
        "mov ecx, DWORD PTR [ebx+4]",
        "mov edx, DWORD PTR [ebx+8]",
        "mov edi, DWORD PTR [ebx+12]",
        "add eax, eax",
        "adc ecx, ecx",
        "adc edx, edx",
        "adc edi, edi",
        "sbb ebp, ebp",
        "and ebp, 135",
        "xor eax, ebp",
        "mov DWORD PTR [ebx], eax",
        "mov DWORD PTR [ebx+4], ecx",
        "mov DWORD PTR [ebx+8], edx",
        "mov DWORD PTR [ebx+12], edi",
        "add esi, 16",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, eax",
        "add eax, eax",
        "add eax, eax",
        "add eax, eax",
        "add eax, DWORD PTR [esp+16]",
        "cmp esi, eax",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov eax, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [eax+2064]",
        "mov esi, DWORD PTR [eax+2068]",
        "mov edi, DWORD PTR [eax+2072]",
        "mov ebp, DWORD PTR [eax+2076]",
        "ret",
        ".p2align 6",
        vg_aes_decrypt_blocks = sym super::aes::vg_aes_decrypt_blocks,
    )
}
