// @generated by lean/Emit.lean. DO NOT EDIT.
//! Verified `aes_cfb8` functions for `x86`.
#![allow(dead_code)]

/// The CPU features `vg_aes_cfb8_encrypt_aesni` requires (`Artifact.features`).
pub(crate) const VG_AES_CFB8_ENCRYPT_AESNI_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["aes"]);

/// AES-CFB8 encryption (NIST SP 800-38A §6.3, with 8-bit segments), in place: replaces the `len` bytes `P#₁ … P#ₙ` at `data` with `C#ⱼ = P#ⱼ ⊕ MSB₈(CIPH_K(Iⱼ))`, where `I₁` is the block at `*iv` and `Iⱼ₊₁` is `Iⱼ` without its first byte, followed by `C#ⱼ`, and `*iv` with `Iₙ₊₁` (leaving it unchanged if `len = 0`), so that a further call continues the message. `CIPH_K` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it.
///
/// Contract: `VG.Spec.Cfb8.aesEncryptContract`. Constant time: only the pointers, `rounds` and `len` may affect timing, not the key schedule, the input block or the data.
///
/// This implementation enciphers one block for each byte with `vg_aes_encrypt_blocks_aesni`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `iv` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `len` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `iv`, `data` and `scratch` must not overlap each other, `schedule` or the arguments on the stack (distinct Rust objects never do).
/// * None of `schedule`, `iv`, `data` and `scratch` may overlap the return address on the stack or the 24 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `aes` target feature.
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_aes_cfb8_encrypt_aesni(schedule: *const [u8; 240], rounds: usize, iv: *mut [u8; 16], data: *mut u8, len: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+24]",
        "mov DWORD PTR [eax+2064], ebx",
        "mov DWORD PTR [eax+2068], esi",
        "mov DWORD PTR [eax+2072], edi",
        "mov DWORD PTR [eax+2076], ebp",
        "mov esi, DWORD PTR [esp+16]",
        "mov eax, DWORD PTR [esp+20]",
        "test eax, eax",
        "je 20f",
        "22:",
        "mov ebp, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [esp+12]",
        "mov eax, 0",
        "mov DWORD PTR [ebp+2048], eax",
        "mov DWORD PTR [ebp+2052], eax",
        "mov DWORD PTR [ebp+2056], eax",
        "mov DWORD PTR [ebp+2060], eax",
        "mov eax, DWORD PTR [ebp+2048]",
        "mov ecx, DWORD PTR [ebx]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2048], eax",
        "mov eax, DWORD PTR [ebp+2052]",
        "mov ecx, DWORD PTR [ebx+4]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2052], eax",
        "mov eax, DWORD PTR [ebp+2056]",
        "mov ecx, DWORD PTR [ebx+8]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2056], eax",
        "mov eax, DWORD PTR [ebp+2060]",
        "mov ecx, DWORD PTR [ebx+12]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2060], eax",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov ebx, ebp",
        "add ebx, 2048",
        "mov edi, 1",
        "push ebp",
        "push edi",
        "push ebx",
        "push ecx",
        "push eax",
        "call {vg_aes_encrypt_blocks_aesni}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ebp, DWORD PTR [esp+24]",
        "movzx eax, BYTE PTR [esi]",
        "movzx ecx, BYTE PTR [ebp+2048]",
        "xor eax, ecx",
        "mov BYTE PTR [esi], al",
        "mov ebx, DWORD PTR [esp+12]",
        "mov ecx, DWORD PTR [ebx+1]",
        "mov edx, DWORD PTR [ebx+5]",
        "mov edi, DWORD PTR [ebx+9]",
        "mov ebp, DWORD PTR [ebx+12]",
        "mov DWORD PTR [ebx], ecx",
        "mov DWORD PTR [ebx+4], edx",
        "mov DWORD PTR [ebx+8], edi",
        "mov DWORD PTR [ebx+11], ebp",
        "mov BYTE PTR [ebx+15], al",
        "add esi, 1",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, DWORD PTR [esp+16]",
        "cmp esi, eax",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov eax, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [eax+2064]",
        "mov esi, DWORD PTR [eax+2068]",
        "mov edi, DWORD PTR [eax+2072]",
        "mov ebp, DWORD PTR [eax+2076]",
        "ret",
        ".p2align 6",
        vg_aes_encrypt_blocks_aesni = sym super::aes::vg_aes_encrypt_blocks_aesni,
    )
}

/// The CPU features `vg_aes_cfb8_decrypt_aesni` requires (`Artifact.features`).
pub(crate) const VG_AES_CFB8_DECRYPT_AESNI_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["aes"]);

/// AES-CFB8 decryption (NIST SP 800-38A §6.3, with 8-bit segments), in place: replaces the `len` bytes `C#₁ … C#ₙ` at `data` with `P#ⱼ = C#ⱼ ⊕ MSB₈(CIPH_K(Iⱼ))`, where `I₁` is the block at `*iv` and `Iⱼ₊₁` is `Iⱼ` without its first byte, followed by `C#ⱼ`, and `*iv` with `Iₙ₊₁` (leaving it unchanged if `len = 0`), so that a further call continues the message. `CIPH_K` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it.
///
/// Contract: `VG.Spec.Cfb8.aesDecryptContract`. Constant time: only the pointers, `rounds` and `len` may affect timing, not the key schedule, the input block or the data.
///
/// This implementation enciphers one block for each byte with `vg_aes_encrypt_blocks_aesni`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `iv` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `len` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `iv`, `data` and `scratch` must not overlap each other, `schedule` or the arguments on the stack (distinct Rust objects never do).
/// * None of `schedule`, `iv`, `data` and `scratch` may overlap the return address on the stack or the 24 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `aes` target feature.
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_aes_cfb8_decrypt_aesni(schedule: *const [u8; 240], rounds: usize, iv: *mut [u8; 16], data: *mut u8, len: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+24]",
        "mov DWORD PTR [eax+2064], ebx",
        "mov DWORD PTR [eax+2068], esi",
        "mov DWORD PTR [eax+2072], edi",
        "mov DWORD PTR [eax+2076], ebp",
        "mov esi, DWORD PTR [esp+16]",
        "mov eax, DWORD PTR [esp+20]",
        "test eax, eax",
        "je 20f",
        "22:",
        "mov ebp, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [esp+12]",
        "mov eax, 0",
        "mov DWORD PTR [ebp+2048], eax",
        "mov DWORD PTR [ebp+2052], eax",
        "mov DWORD PTR [ebp+2056], eax",
        "mov DWORD PTR [ebp+2060], eax",
        "mov eax, DWORD PTR [ebp+2048]",
        "mov ecx, DWORD PTR [ebx]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2048], eax",
        "mov eax, DWORD PTR [ebp+2052]",
        "mov ecx, DWORD PTR [ebx+4]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2052], eax",
        "mov eax, DWORD PTR [ebp+2056]",
        "mov ecx, DWORD PTR [ebx+8]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2056], eax",
        "mov eax, DWORD PTR [ebp+2060]",
        "mov ecx, DWORD PTR [ebx+12]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2060], eax",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov ebx, ebp",
        "add ebx, 2048",
        "mov edi, 1",
        "push ebp",
        "push edi",
        "push ebx",
        "push ecx",
        "push eax",
        "call {vg_aes_encrypt_blocks_aesni}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ebp, DWORD PTR [esp+24]",
        "movzx eax, BYTE PTR [esi]",
        "movzx ecx, BYTE PTR [ebp+2048]",
        "xor ecx, eax",
        "mov BYTE PTR [esi], cl",
        "mov ebx, DWORD PTR [esp+12]",
        "mov ecx, DWORD PTR [ebx+1]",
        "mov edx, DWORD PTR [ebx+5]",
        "mov edi, DWORD PTR [ebx+9]",
        "mov ebp, DWORD PTR [ebx+12]",
        "mov DWORD PTR [ebx], ecx",
        "mov DWORD PTR [ebx+4], edx",
        "mov DWORD PTR [ebx+8], edi",
        "mov DWORD PTR [ebx+11], ebp",
        "mov BYTE PTR [ebx+15], al",
        "add esi, 1",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, DWORD PTR [esp+16]",
        "cmp esi, eax",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov eax, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [eax+2064]",
        "mov esi, DWORD PTR [eax+2068]",
        "mov edi, DWORD PTR [eax+2072]",
        "mov ebp, DWORD PTR [eax+2076]",
        "ret",
        ".p2align 6",
        vg_aes_encrypt_blocks_aesni = sym super::aes::vg_aes_encrypt_blocks_aesni,
    )
}

/// AES-CFB8 encryption (NIST SP 800-38A §6.3, with 8-bit segments), in place: replaces the `len` bytes `P#₁ … P#ₙ` at `data` with `C#ⱼ = P#ⱼ ⊕ MSB₈(CIPH_K(Iⱼ))`, where `I₁` is the block at `*iv` and `Iⱼ₊₁` is `Iⱼ` without its first byte, followed by `C#ⱼ`, and `*iv` with `Iₙ₊₁` (leaving it unchanged if `len = 0`), so that a further call continues the message. `CIPH_K` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it.
///
/// Contract: `VG.Spec.Cfb8.aesEncryptContract`. Constant time: only the pointers, `rounds` and `len` may affect timing, not the key schedule, the input block or the data.
///
/// This implementation enciphers one block for each byte with `vg_aes_encrypt_blocks`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `iv` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `len` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `iv`, `data` and `scratch` must not overlap each other, `schedule` or the arguments on the stack (distinct Rust objects never do).
/// * None of `schedule`, `iv`, `data` and `scratch` may overlap the return address on the stack or the 24 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_aes_cfb8_encrypt(schedule: *const [u8; 240], rounds: usize, iv: *mut [u8; 16], data: *mut u8, len: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+24]",
        "mov DWORD PTR [eax+2064], ebx",
        "mov DWORD PTR [eax+2068], esi",
        "mov DWORD PTR [eax+2072], edi",
        "mov DWORD PTR [eax+2076], ebp",
        "mov esi, DWORD PTR [esp+16]",
        "mov eax, DWORD PTR [esp+20]",
        "test eax, eax",
        "je 20f",
        "22:",
        "mov ebp, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [esp+12]",
        "mov eax, 0",
        "mov DWORD PTR [ebp+2048], eax",
        "mov DWORD PTR [ebp+2052], eax",
        "mov DWORD PTR [ebp+2056], eax",
        "mov DWORD PTR [ebp+2060], eax",
        "mov eax, DWORD PTR [ebp+2048]",
        "mov ecx, DWORD PTR [ebx]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2048], eax",
        "mov eax, DWORD PTR [ebp+2052]",
        "mov ecx, DWORD PTR [ebx+4]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2052], eax",
        "mov eax, DWORD PTR [ebp+2056]",
        "mov ecx, DWORD PTR [ebx+8]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2056], eax",
        "mov eax, DWORD PTR [ebp+2060]",
        "mov ecx, DWORD PTR [ebx+12]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2060], eax",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov ebx, ebp",
        "add ebx, 2048",
        "mov edi, 1",
        "push ebp",
        "push edi",
        "push ebx",
        "push ecx",
        "push eax",
        "call {vg_aes_encrypt_blocks}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ebp, DWORD PTR [esp+24]",
        "movzx eax, BYTE PTR [esi]",
        "movzx ecx, BYTE PTR [ebp+2048]",
        "xor eax, ecx",
        "mov BYTE PTR [esi], al",
        "mov ebx, DWORD PTR [esp+12]",
        "mov ecx, DWORD PTR [ebx+1]",
        "mov edx, DWORD PTR [ebx+5]",
        "mov edi, DWORD PTR [ebx+9]",
        "mov ebp, DWORD PTR [ebx+12]",
        "mov DWORD PTR [ebx], ecx",
        "mov DWORD PTR [ebx+4], edx",
        "mov DWORD PTR [ebx+8], edi",
        "mov DWORD PTR [ebx+11], ebp",
        "mov BYTE PTR [ebx+15], al",
        "add esi, 1",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, DWORD PTR [esp+16]",
        "cmp esi, eax",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov eax, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [eax+2064]",
        "mov esi, DWORD PTR [eax+2068]",
        "mov edi, DWORD PTR [eax+2072]",
        "mov ebp, DWORD PTR [eax+2076]",
        "ret",
        ".p2align 6",
        vg_aes_encrypt_blocks = sym super::aes::vg_aes_encrypt_blocks,
    )
}

/// AES-CFB8 decryption (NIST SP 800-38A §6.3, with 8-bit segments), in place: replaces the `len` bytes `C#₁ … C#ₙ` at `data` with `P#ⱼ = C#ⱼ ⊕ MSB₈(CIPH_K(Iⱼ))`, where `I₁` is the block at `*iv` and `Iⱼ₊₁` is `Iⱼ` without its first byte, followed by `C#ⱼ`, and `*iv` with `Iₙ₊₁` (leaving it unchanged if `len = 0`), so that a further call continues the message. `CIPH_K` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it.
///
/// Contract: `VG.Spec.Cfb8.aesDecryptContract`. Constant time: only the pointers, `rounds` and `len` may affect timing, not the key schedule, the input block or the data.
///
/// This implementation enciphers one block for each byte with `vg_aes_encrypt_blocks`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `iv` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `len` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `iv`, `data` and `scratch` must not overlap each other, `schedule` or the arguments on the stack (distinct Rust objects never do).
/// * None of `schedule`, `iv`, `data` and `scratch` may overlap the return address on the stack or the 24 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_aes_cfb8_decrypt(schedule: *const [u8; 240], rounds: usize, iv: *mut [u8; 16], data: *mut u8, len: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+24]",
        "mov DWORD PTR [eax+2064], ebx",
        "mov DWORD PTR [eax+2068], esi",
        "mov DWORD PTR [eax+2072], edi",
        "mov DWORD PTR [eax+2076], ebp",
        "mov esi, DWORD PTR [esp+16]",
        "mov eax, DWORD PTR [esp+20]",
        "test eax, eax",
        "je 20f",
        "22:",
        "mov ebp, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [esp+12]",
        "mov eax, 0",
        "mov DWORD PTR [ebp+2048], eax",
        "mov DWORD PTR [ebp+2052], eax",
        "mov DWORD PTR [ebp+2056], eax",
        "mov DWORD PTR [ebp+2060], eax",
        "mov eax, DWORD PTR [ebp+2048]",
        "mov ecx, DWORD PTR [ebx]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2048], eax",
        "mov eax, DWORD PTR [ebp+2052]",
        "mov ecx, DWORD PTR [ebx+4]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2052], eax",
        "mov eax, DWORD PTR [ebp+2056]",
        "mov ecx, DWORD PTR [ebx+8]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2056], eax",
        "mov eax, DWORD PTR [ebp+2060]",
        "mov ecx, DWORD PTR [ebx+12]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2060], eax",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov ebx, ebp",
        "add ebx, 2048",
        "mov edi, 1",
        "push ebp",
        "push edi",
        "push ebx",
        "push ecx",
        "push eax",
        "call {vg_aes_encrypt_blocks}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ebp, DWORD PTR [esp+24]",
        "movzx eax, BYTE PTR [esi]",
        "movzx ecx, BYTE PTR [ebp+2048]",
        "xor ecx, eax",
        "mov BYTE PTR [esi], cl",
        "mov ebx, DWORD PTR [esp+12]",
        "mov ecx, DWORD PTR [ebx+1]",
        "mov edx, DWORD PTR [ebx+5]",
        "mov edi, DWORD PTR [ebx+9]",
        "mov ebp, DWORD PTR [ebx+12]",
        "mov DWORD PTR [ebx], ecx",
        "mov DWORD PTR [ebx+4], edx",
        "mov DWORD PTR [ebx+8], edi",
        "mov DWORD PTR [ebx+11], ebp",
        "mov BYTE PTR [ebx+15], al",
        "add esi, 1",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, DWORD PTR [esp+16]",
        "cmp esi, eax",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov eax, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [eax+2064]",
        "mov esi, DWORD PTR [eax+2068]",
        "mov edi, DWORD PTR [eax+2072]",
        "mov ebp, DWORD PTR [eax+2076]",
        "ret",
        ".p2align 6",
        vg_aes_encrypt_blocks = sym super::aes::vg_aes_encrypt_blocks,
    )
}
