// @generated by lean/Emit.lean. DO NOT EDIT.
//! Verified `aes_ofb` functions for `x86`.
#![allow(dead_code)]

/// The CPU features `vg_aes_ofb_aesni` requires (`Artifact.features`).
pub(crate) const VG_AES_OFB_AESNI_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["aes"]);

/// AES-OFB encryption or decryption (NIST SP 800-38A §6.4) of whole blocks, in place: XORs the `n` 16-byte blocks at `data` with the output blocks `Oⱼ = CIPH_K(Oⱼ₋₁)`, where `O₀` is the block at `*iv`, and replaces `*iv` with `Oₙ` (leaving it unchanged if `n = 0`), so that a further call continues the message. `CIPH_K` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it.
///
/// Contract: `VG.Spec.Ofb.aesContract`. Constant time: only the pointers, `rounds` and `n` may affect timing, not the key schedule, the chaining value or the data.
///
/// This implementation enciphers one block at a time with `vg_aes_encrypt_blocks_aesni`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `iv` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `iv`, `data` and `scratch` must not overlap each other, `schedule` or the arguments on the stack (distinct Rust objects never do).
/// * None of `schedule`, `iv`, `data` and `scratch` may overlap the return address on the stack or the 24 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `aes` target feature.
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_aes_ofb_aesni(schedule: *const [u8; 240], rounds: usize, iv: *mut [u8; 16], data: *mut [u8; 16], n: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+24]",
        "mov DWORD PTR [eax+2064], ebx",
        "mov DWORD PTR [eax+2068], esi",
        "mov DWORD PTR [eax+2072], edi",
        "mov DWORD PTR [eax+2076], ebp",
        "mov esi, DWORD PTR [esp+16]",
        "mov eax, DWORD PTR [esp+20]",
        "test eax, eax",
        "je 20f",
        "22:",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov ebx, DWORD PTR [esp+12]",
        "mov edi, 1",
        "mov ebp, DWORD PTR [esp+24]",
        "push ebp",
        "push edi",
        "push ebx",
        "push ecx",
        "push eax",
        "call {vg_aes_encrypt_blocks_aesni}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ebx, DWORD PTR [esp+12]",
        "mov eax, DWORD PTR [esi]",
        "mov ecx, DWORD PTR [ebx]",
        "xor eax, ecx",
        "mov DWORD PTR [esi], eax",
        "mov eax, DWORD PTR [esi+4]",
        "mov ecx, DWORD PTR [ebx+4]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+4], eax",
        "mov eax, DWORD PTR [esi+8]",
        "mov ecx, DWORD PTR [ebx+8]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+8], eax",
        "mov eax, DWORD PTR [esi+12]",
        "mov ecx, DWORD PTR [ebx+12]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+12], eax",
        "add esi, 16",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, eax",
        "add eax, eax",
        "add eax, eax",
        "add eax, eax",
        "add eax, DWORD PTR [esp+16]",
        "cmp esi, eax",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov eax, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [eax+2064]",
        "mov esi, DWORD PTR [eax+2068]",
        "mov edi, DWORD PTR [eax+2072]",
        "mov ebp, DWORD PTR [eax+2076]",
        "ret",
        ".p2align 6",
        vg_aes_encrypt_blocks_aesni = sym super::aes::vg_aes_encrypt_blocks_aesni,
    )
}

/// AES-OFB encryption or decryption (NIST SP 800-38A §6.4) of whole blocks, in place: XORs the `n` 16-byte blocks at `data` with the output blocks `Oⱼ = CIPH_K(Oⱼ₋₁)`, where `O₀` is the block at `*iv`, and replaces `*iv` with `Oₙ` (leaving it unchanged if `n = 0`), so that a further call continues the message. `CIPH_K` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it.
///
/// Contract: `VG.Spec.Ofb.aesContract`. Constant time: only the pointers, `rounds` and `n` may affect timing, not the key schedule, the chaining value or the data.
///
/// This implementation enciphers one block at a time with `vg_aes_encrypt_blocks`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `iv` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `iv`, `data` and `scratch` must not overlap each other, `schedule` or the arguments on the stack (distinct Rust objects never do).
/// * None of `schedule`, `iv`, `data` and `scratch` may overlap the return address on the stack or the 24 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_aes_ofb(schedule: *const [u8; 240], rounds: usize, iv: *mut [u8; 16], data: *mut [u8; 16], n: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+24]",
        "mov DWORD PTR [eax+2064], ebx",
        "mov DWORD PTR [eax+2068], esi",
        "mov DWORD PTR [eax+2072], edi",
        "mov DWORD PTR [eax+2076], ebp",
        "mov esi, DWORD PTR [esp+16]",
        "mov eax, DWORD PTR [esp+20]",
        "test eax, eax",
        "je 20f",
        "22:",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov ebx, DWORD PTR [esp+12]",
        "mov edi, 1",
        "mov ebp, DWORD PTR [esp+24]",
        "push ebp",
        "push edi",
        "push ebx",
        "push ecx",
        "push eax",
        "call {vg_aes_encrypt_blocks}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ebx, DWORD PTR [esp+12]",
        "mov eax, DWORD PTR [esi]",
        "mov ecx, DWORD PTR [ebx]",
        "xor eax, ecx",
        "mov DWORD PTR [esi], eax",
        "mov eax, DWORD PTR [esi+4]",
        "mov ecx, DWORD PTR [ebx+4]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+4], eax",
        "mov eax, DWORD PTR [esi+8]",
        "mov ecx, DWORD PTR [ebx+8]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+8], eax",
        "mov eax, DWORD PTR [esi+12]",
        "mov ecx, DWORD PTR [ebx+12]",
        "xor eax, ecx",
        "mov DWORD PTR [esi+12], eax",
        "add esi, 16",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, eax",
        "add eax, eax",
        "add eax, eax",
        "add eax, eax",
        "add eax, DWORD PTR [esp+16]",
        "cmp esi, eax",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov eax, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [eax+2064]",
        "mov esi, DWORD PTR [eax+2068]",
        "mov edi, DWORD PTR [eax+2072]",
        "mov ebp, DWORD PTR [eax+2076]",
        "ret",
        ".p2align 6",
        vg_aes_encrypt_blocks = sym super::aes::vg_aes_encrypt_blocks,
    )
}
