// @generated by lean/Emit.lean. DO NOT EDIT.
//! Verified `cmac_aes` functions for `x86`.
#![allow(dead_code)]

/// The CPU features `vg_cmac_aes_subkeys_aesni` requires (`Artifact.features`).
pub(crate) const VG_CMAC_AES_SUBKEYS_AESNI_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["aes"]);

/// The CMAC subkey generation (NIST SP 800-38B §6.1) for AES: writes `K1 ‖ K2` to `*subkeys`, where `L = CIPH_K(0¹²⁸)`, `K1 = L << 1` (XORed with `R₁₂₈ = 0¹²⁰10000111` if the leftmost bit of `L` is 1) and `K2` is `K1` doubled the same way. `CIPH_K` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it.
///
/// Contract: `VG.Spec.Cmac.aesSubkeysContract`. Constant time: only the pointers and `rounds` may affect timing, not the key schedule or the subkeys.
///
/// This implementation encrypts each block with `vg_aes_ctr32_aesni`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `subkeys` must be valid for reads and writes of 32 bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `subkeys` and `scratch` must not overlap each other, `schedule` or the arguments on the stack (distinct Rust objects never do).
/// * None of `schedule`, `subkeys` and `scratch` may overlap the return address on the stack or the 28 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `aes` target feature.
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_cmac_aes_subkeys_aesni(schedule: *const [u8; 240], rounds: usize, subkeys: *mut [u8; 32], scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+16]",
        "mov DWORD PTR [eax+2064], ebx",
        "mov DWORD PTR [eax+2068], esi",
        "mov DWORD PTR [eax+2072], edi",
        "mov DWORD PTR [eax+2076], ebp",
        "mov ebp, eax",
        "mov ebx, DWORD PTR [esp+12]",
        "mov eax, 0",
        "mov DWORD PTR [ebp+2048], eax",
        "mov DWORD PTR [ebp+2052], eax",
        "mov DWORD PTR [ebp+2056], eax",
        "mov DWORD PTR [ebp+2060], eax",
        "mov eax, 0",
        "mov DWORD PTR [ebx], eax",
        "mov DWORD PTR [ebx+4], eax",
        "mov DWORD PTR [ebx+8], eax",
        "mov DWORD PTR [ebx+12], eax",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov edx, ebp",
        "add edx, 2048",
        "mov edi, 1",
        "push ebp",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_aes_ctr32_aesni}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [ebx]",
        "mov ecx, DWORD PTR [ebx+4]",
        "mov edx, DWORD PTR [ebx+8]",
        "mov esi, DWORD PTR [ebx+12]",
        "bswap eax",
        "bswap ecx",
        "bswap edx",
        "bswap esi",
        "mov edi, eax",
        "shr edi, 31",
        "mov ebp, 0",
        "sub ebp, edi",
        "and ebp, 135",
        "add eax, eax",
        "mov edi, ecx",
        "shr edi, 31",
        "or eax, edi",
        "add ecx, ecx",
        "mov edi, edx",
        "shr edi, 31",
        "or ecx, edi",
        "add edx, edx",
        "mov edi, esi",
        "shr edi, 31",
        "or edx, edi",
        "add esi, esi",
        "xor esi, ebp",
        "bswap eax",
        "bswap ecx",
        "bswap edx",
        "bswap esi",
        "mov DWORD PTR [ebx], eax",
        "mov DWORD PTR [ebx+4], ecx",
        "mov DWORD PTR [ebx+8], edx",
        "mov DWORD PTR [ebx+12], esi",
        "mov eax, DWORD PTR [ebx]",
        "mov ecx, DWORD PTR [ebx+4]",
        "mov edx, DWORD PTR [ebx+8]",
        "mov esi, DWORD PTR [ebx+12]",
        "bswap eax",
        "bswap ecx",
        "bswap edx",
        "bswap esi",
        "mov edi, eax",
        "shr edi, 31",
        "mov ebp, 0",
        "sub ebp, edi",
        "and ebp, 135",
        "add eax, eax",
        "mov edi, ecx",
        "shr edi, 31",
        "or eax, edi",
        "add ecx, ecx",
        "mov edi, edx",
        "shr edi, 31",
        "or ecx, edi",
        "add edx, edx",
        "mov edi, esi",
        "shr edi, 31",
        "or edx, edi",
        "add esi, esi",
        "xor esi, ebp",
        "bswap eax",
        "bswap ecx",
        "bswap edx",
        "bswap esi",
        "mov DWORD PTR [ebx+16], eax",
        "mov DWORD PTR [ebx+20], ecx",
        "mov DWORD PTR [ebx+24], edx",
        "mov DWORD PTR [ebx+28], esi",
        "mov eax, DWORD PTR [esp+16]",
        "mov ebx, DWORD PTR [eax+2064]",
        "mov esi, DWORD PTR [eax+2068]",
        "mov edi, DWORD PTR [eax+2072]",
        "mov ebp, DWORD PTR [eax+2076]",
        "ret",
        ".p2align 6",
        vg_aes_ctr32_aesni = sym super::aes::vg_aes_ctr32_aesni,
    )
}

/// The CPU features `vg_cmac_aes_update_aesni` requires (`Artifact.features`).
pub(crate) const VG_CMAC_AES_UPDATE_AESNI_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["aes"]);

/// CMAC's chaining (NIST SP 800-38B §6.2 step 6) for AES, over whole blocks: replaces the block `C₀` at `*state` with `Cₙ`, where `Cᵢ = CIPH_K(Cᵢ₋₁ ⊕ Mᵢ)` for the `n` 16-byte blocks `M₁ … Mₙ` starting at `data`. `CIPH_K` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it.
///
/// Contract: `VG.Spec.Cmac.aesUpdateContract`. Constant time: only the pointers, `rounds` and `n` may affect timing, not the key schedule, the chaining value or the data.
///
/// This implementation encrypts each block with `vg_aes_ctr32_aesni`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `state` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `state` and `scratch` must not overlap each other, `schedule`, `data` or the arguments on the stack (distinct Rust objects never do).
/// * None of `schedule`, `state`, `data` and `scratch` may overlap the return address on the stack or the 28 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `aes` target feature.
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_cmac_aes_update_aesni(schedule: *const [u8; 240], rounds: usize, state: *mut [u8; 16], data: *const [u8; 16], n: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+24]",
        "mov DWORD PTR [eax+2064], ebx",
        "mov DWORD PTR [eax+2068], esi",
        "mov DWORD PTR [eax+2072], edi",
        "mov DWORD PTR [eax+2076], ebp",
        "mov esi, DWORD PTR [esp+16]",
        "mov eax, DWORD PTR [esp+20]",
        "test eax, eax",
        "je 20f",
        "22:",
        "mov ebx, DWORD PTR [esp+12]",
        "mov ebp, DWORD PTR [esp+24]",
        "mov eax, DWORD PTR [ebx]",
        "mov ecx, DWORD PTR [esi]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2048], eax",
        "mov eax, DWORD PTR [ebx+4]",
        "mov ecx, DWORD PTR [esi+4]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2052], eax",
        "mov eax, DWORD PTR [ebx+8]",
        "mov ecx, DWORD PTR [esi+8]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2056], eax",
        "mov eax, DWORD PTR [ebx+12]",
        "mov ecx, DWORD PTR [esi+12]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2060], eax",
        "mov eax, 0",
        "mov DWORD PTR [ebx], eax",
        "mov DWORD PTR [ebx+4], eax",
        "mov DWORD PTR [ebx+8], eax",
        "mov DWORD PTR [ebx+12], eax",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov edx, ebp",
        "add edx, 2048",
        "mov edi, 1",
        "push ebp",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_aes_ctr32_aesni}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "add esi, 16",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, eax",
        "add eax, eax",
        "add eax, eax",
        "add eax, eax",
        "add eax, DWORD PTR [esp+16]",
        "cmp esi, eax",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov eax, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [eax+2064]",
        "mov esi, DWORD PTR [eax+2068]",
        "mov edi, DWORD PTR [eax+2072]",
        "mov ebp, DWORD PTR [eax+2076]",
        "ret",
        ".p2align 6",
        vg_aes_ctr32_aesni = sym super::aes::vg_aes_ctr32_aesni,
    )
}

/// The CPU features `vg_cmac_aes_finalize_aesni` requires (`Artifact.features`).
pub(crate) const VG_CMAC_AES_FINALIZE_AESNI_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["aes"]);

/// Finishes an AES-CMAC computation (NIST SP 800-38B §6.2, with `Tlen = 128`): if the block at `*state` is the chaining value `Cₙ₋₁` of the message's blocks but the last (as `vg_cmac_aes_update` computes it from a zero block), and the `last_len` bytes at `last` are the message's last bytes `Mₙ*`, replaces it with the MAC `Cₙ = CIPH_K(Cₙ₋₁ ⊕ Mₙ)`, where `Mₙ = K1 ⊕ Mₙ*` if `last_len` is 16, and `Mₙ = K2 ⊕ (Mₙ* ‖ 10ʲ)` otherwise. `*key` is the 240 bytes `vg_aes_expand_key` writes the key schedule for `rounds` rounds to, followed by the subkeys `K1 ‖ K2` (as `vg_cmac_aes_subkeys` writes them). `last_len` is 0 only for the empty message.
///
/// Contract: `VG.Spec.Cmac.aesFinalizeContract`. Constant time: only the pointers, `rounds` and `last_len` may affect timing, not the key schedule, the subkeys, the chaining value or the data.
///
/// This implementation encrypts each block with `vg_aes_ctr32_aesni`.
///
/// # Safety
///
/// * `key` must be valid for reads of 272 bytes.
/// * `state` must be valid for reads and writes of 16 bytes.
/// * `last` must be valid for reads of `last_len` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * `last_len` must be at most 16.
/// * The contents of `scratch` on return are unspecified.
/// * `state` and `scratch` must not overlap each other, `key`, `last` or the arguments on the stack (distinct Rust objects never do).
/// * None of `key`, `state`, `last` and `scratch` may overlap the return address on the stack or the 28 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `aes` target feature.
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_cmac_aes_finalize_aesni(key: *const [u8; 272], rounds: usize, state: *mut [u8; 16], last: *const u8, last_len: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+24]",
        "mov DWORD PTR [eax+2064], ebx",
        "mov DWORD PTR [eax+2068], esi",
        "mov DWORD PTR [eax+2072], edi",
        "mov DWORD PTR [eax+2076], ebp",
        "mov ebp, eax",
        "mov ecx, DWORD PTR [esp+20]",
        "cmp ecx, 16",
        "je 20f",
        "mov eax, 0",
        "mov DWORD PTR [ebp+2048], eax",
        "mov DWORD PTR [ebp+2052], eax",
        "mov DWORD PTR [ebp+2056], eax",
        "mov DWORD PTR [ebp+2060], eax",
        "mov edi, ebp",
        "add edi, 2048",
        "mov esi, DWORD PTR [esp+16]",
        "mov ecx, DWORD PTR [esp+20]",
        "test ecx, ecx",
        "je 22f",
        "24:",
        "movzx eax, BYTE PTR [esi]",
        "mov BYTE PTR [edi], al",
        "add esi, 1",
        "add edi, 1",
        "sub ecx, 1",
        "jne 24b",
        "jmp 23f",
        "22:",
        "23:",
        "mov eax, 128",
        "mov BYTE PTR [edi], al",
        "mov edx, DWORD PTR [esp+4]",
        "mov eax, DWORD PTR [ebp+2048]",
        "mov ecx, DWORD PTR [edx+256]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2048], eax",
        "mov eax, DWORD PTR [ebp+2052]",
        "mov ecx, DWORD PTR [edx+260]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2052], eax",
        "mov eax, DWORD PTR [ebp+2056]",
        "mov ecx, DWORD PTR [edx+264]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2056], eax",
        "mov eax, DWORD PTR [ebp+2060]",
        "mov ecx, DWORD PTR [edx+268]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2060], eax",
        "jmp 21f",
        "20:",
        "mov ebx, DWORD PTR [esp+16]",
        "mov edx, DWORD PTR [esp+4]",
        "mov eax, DWORD PTR [ebx]",
        "mov ecx, DWORD PTR [edx+240]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2048], eax",
        "mov eax, DWORD PTR [ebx+4]",
        "mov ecx, DWORD PTR [edx+244]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2052], eax",
        "mov eax, DWORD PTR [ebx+8]",
        "mov ecx, DWORD PTR [edx+248]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2056], eax",
        "mov eax, DWORD PTR [ebx+12]",
        "mov ecx, DWORD PTR [edx+252]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2060], eax",
        "21:",
        "mov ebx, DWORD PTR [esp+12]",
        "mov eax, DWORD PTR [ebp+2048]",
        "mov ecx, DWORD PTR [ebx]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2048], eax",
        "mov eax, DWORD PTR [ebp+2052]",
        "mov ecx, DWORD PTR [ebx+4]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2052], eax",
        "mov eax, DWORD PTR [ebp+2056]",
        "mov ecx, DWORD PTR [ebx+8]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2056], eax",
        "mov eax, DWORD PTR [ebp+2060]",
        "mov ecx, DWORD PTR [ebx+12]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2060], eax",
        "mov eax, 0",
        "mov DWORD PTR [ebx], eax",
        "mov DWORD PTR [ebx+4], eax",
        "mov DWORD PTR [ebx+8], eax",
        "mov DWORD PTR [ebx+12], eax",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov edx, ebp",
        "add edx, 2048",
        "mov edi, 1",
        "push ebp",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_aes_ctr32_aesni}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [eax+2064]",
        "mov esi, DWORD PTR [eax+2068]",
        "mov edi, DWORD PTR [eax+2072]",
        "mov ebp, DWORD PTR [eax+2076]",
        "ret",
        ".p2align 6",
        vg_aes_ctr32_aesni = sym super::aes::vg_aes_ctr32_aesni,
    )
}

/// The CPU features `vg_cmac_aes_init_aesni` requires (`Artifact.features`).
pub(crate) const VG_CMAC_AES_INIT_AESNI_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["aes"]);

/// Starts an AES-CMAC computation (NIST SP 800-38B, RFC 4493): makes the streaming state `*state` represent the empty message under the AES key of `key_len` bytes at `key` (AES-128, AES-192 or AES-256). The state holds the key schedule of AES (FIPS 197) with `key_len / 4 + 6` rounds, the subkeys `K1 ‖ K2` (§6.1), the chaining value and the message's last bytes, held back (`VG.Spec.Cmac.Repr`). Continue with `vg_cmac_aes_absorb` and `vg_cmac_aes_finish`, passing them `key_len / 4 + 6` as `rounds`.
///
/// Contract: `VG.Spec.Cmac.aesInitContract`. Constant time: only the pointers and `key_len` may affect timing, not the key.
///
/// This implementation calls the CMAC functions made with `vg_aes_ctr32_aesni` (e.g. `vg_cmac_aes_update_aesni`).
///
/// It expands the key with `vg_aes_expand_key_aesni`.
///
/// # Safety
///
/// * `state` must be valid for reads and writes of 304 bytes.
/// * `key` must be valid for reads of `key_len` bytes.
/// * `scratch` must be valid for reads and writes of 2304 bytes.
/// * `key_len` must be 16, 24 or 32.
/// * The contents of `scratch` on return are unspecified.
/// * `state` and `scratch` must not overlap each other, `key` or the arguments on the stack (distinct Rust objects never do).
/// * None of `state`, `key` and `scratch` may overlap the return address on the stack or the 48 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `aes` target feature.
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_cmac_aes_init_aesni(state: *mut [u64; 38], key: *const u8, key_len: usize, scratch: *mut [u64; 288]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+16]",
        "mov DWORD PTR [eax+2176], ebx",
        "mov DWORD PTR [eax+2180], esi",
        "mov DWORD PTR [eax+2184], edi",
        "mov DWORD PTR [eax+2188], ebp",
        "mov eax, DWORD PTR [esp+8]",
        "mov ecx, DWORD PTR [esp+12]",
        "mov edx, DWORD PTR [esp+4]",
        "mov ebx, DWORD PTR [esp+16]",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_aes_expand_key_aesni}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+12]",
        "shr ecx, 2",
        "add ecx, 6",
        "mov edx, eax",
        "add edx, 240",
        "mov ebx, DWORD PTR [esp+16]",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_cmac_aes_subkeys_aesni}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov edx, DWORD PTR [esp+4]",
        "mov eax, 0",
        "mov DWORD PTR [edx+272], eax",
        "mov DWORD PTR [edx+276], eax",
        "mov DWORD PTR [edx+280], eax",
        "mov DWORD PTR [edx+284], eax",
        "mov eax, DWORD PTR [esp+16]",
        "mov ebx, DWORD PTR [eax+2176]",
        "mov esi, DWORD PTR [eax+2180]",
        "mov edi, DWORD PTR [eax+2184]",
        "mov ebp, DWORD PTR [eax+2188]",
        "ret",
        ".p2align 6",
        vg_aes_expand_key_aesni = sym super::aes::vg_aes_expand_key_aesni,
        vg_cmac_aes_subkeys_aesni = sym super::cmac_aes::vg_cmac_aes_subkeys_aesni,
    )
}

/// The CPU features `vg_cmac_aes_absorb_aesni` requires (`Artifact.features`).
pub(crate) const VG_CMAC_AES_ABSORB_AESNI_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["aes"]);

/// Absorbs data into an AES-CMAC computation (NIST SP 800-38B §6.2): if the streaming state `*state` represents a message of `count` bytes under an AES key with `rounds` rounds (as `vg_cmac_aes_init` set it up), it then represents that message followed by the `len` bytes at `data`, under the same key, provided that the two together are shorter than 2⁶⁴ bytes. It chains (step 6) every block of the message but its last bytes `Mₙ*` (step 3), which it holds back in the state, since only `vg_cmac_aes_finish` knows they are the last.
///
/// Contract: `VG.Spec.Cmac.aesAbsorbContract`. Constant time: only the pointers, `rounds`, `count` and `len` may affect timing, not the state or the data.
///
/// This implementation calls the CMAC functions made with `vg_aes_ctr32_aesni` (e.g. `vg_cmac_aes_update_aesni`).
///
/// # Safety
///
/// * `state` must be valid for reads and writes of 304 bytes.
/// * `data` must be valid for reads of `len` bytes.
/// * `scratch` must be valid for reads and writes of 2304 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `state` and `scratch` must not overlap each other, `data` or the arguments on the stack (distinct Rust objects never do).
/// * None of `state`, `data` and `scratch` may overlap the return address on the stack or the 56 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `aes` target feature.
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_cmac_aes_absorb_aesni(state: *mut [u64; 38], rounds: usize, count: u64, data: *const u8, len: usize, scratch: *mut [u64; 288]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+28]",
        "mov DWORD PTR [eax+2176], ebx",
        "mov DWORD PTR [eax+2180], esi",
        "mov DWORD PTR [eax+2184], edi",
        "mov DWORD PTR [eax+2188], ebp",
        "mov eax, DWORD PTR [esp+12]",
        "mov ecx, DWORD PTR [esp+16]",
        "or ecx, eax",
        "je 20f",
        "sub eax, 1",
        "and eax, 15",
        "add eax, 1",
        "jmp 21f",
        "20:",
        "21:",
        "mov ecx, 16",
        "sub ecx, eax",
        "mov edx, DWORD PTR [esp+24]",
        "cmp edx, ecx",
        "jb 22f",
        "jmp 23f",
        "22:",
        "mov ecx, edx",
        "23:",
        "mov ebp, ecx",
        "mov esi, DWORD PTR [esp+20]",
        "mov edi, DWORD PTR [esp+4]",
        "add edi, 288",
        "add edi, eax",
        "test ecx, ecx",
        "je 24f",
        "26:",
        "movzx eax, BYTE PTR [esi]",
        "mov BYTE PTR [edi], al",
        "add esi, 1",
        "add edi, 1",
        "sub ecx, 1",
        "jne 26b",
        "jmp 25f",
        "24:",
        "25:",
        "mov esi, 0",
        "mov edx, DWORD PTR [esp+24]",
        "sub edx, ebp",
        "je 27f",
        "mov esi, 1",
        "jmp 28f",
        "27:",
        "28:",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov edx, eax",
        "add edx, 272",
        "mov ebx, eax",
        "add ebx, 288",
        "mov edi, DWORD PTR [esp+28]",
        "push edi",
        "push esi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_cmac_aes_update_aesni}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ecx, 0",
        "mov ebx, DWORD PTR [esp+4]",
        "add ebx, 288",
        "mov edx, DWORD PTR [esp+24]",
        "sub edx, ebp",
        "je 29f",
        "mov ecx, edx",
        "sub ecx, 1",
        "mov eax, ecx",
        "and eax, 15",
        "sub ecx, eax",
        "mov ebx, DWORD PTR [esp+20]",
        "add ebx, ebp",
        "jmp 210f",
        "29:",
        "210:",
        "mov esi, ecx",
        "shr esi, 4",
        "add ebp, ecx",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov edx, eax",
        "add edx, 272",
        "mov edi, DWORD PTR [esp+28]",
        "push edi",
        "push esi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_cmac_aes_update_aesni}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov esi, DWORD PTR [esp+20]",
        "add esi, ebp",
        "mov edi, DWORD PTR [esp+4]",
        "add edi, 288",
        "mov ecx, DWORD PTR [esp+24]",
        "sub ecx, ebp",
        "test ecx, ecx",
        "je 211f",
        "213:",
        "movzx eax, BYTE PTR [esi]",
        "mov BYTE PTR [edi], al",
        "add esi, 1",
        "add edi, 1",
        "sub ecx, 1",
        "jne 213b",
        "jmp 212f",
        "211:",
        "212:",
        "mov eax, DWORD PTR [esp+28]",
        "mov ebx, DWORD PTR [eax+2176]",
        "mov esi, DWORD PTR [eax+2180]",
        "mov edi, DWORD PTR [eax+2184]",
        "mov ebp, DWORD PTR [eax+2188]",
        "ret",
        ".p2align 6",
        vg_cmac_aes_update_aesni = sym super::cmac_aes::vg_cmac_aes_update_aesni,
    )
}

/// The CPU features `vg_cmac_aes_finish_aesni` requires (`Artifact.features`).
pub(crate) const VG_CMAC_AES_FINISH_AESNI_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["aes"]);

/// Finishes an AES-CMAC computation (NIST SP 800-38B §6.2, with `Tlen = 128`): if the streaming state `*state` represents a message of `count` bytes, shorter than 2⁶⁴ bytes, under an AES key with `rounds` rounds (as `vg_cmac_aes_init` and `vg_cmac_aes_absorb` set it up), writes the MAC of that message under that key to `*out`: `Cₙ = CIPH_K(Cₙ₋₁ ⊕ Mₙ)`, where `Mₙ = K1 ⊕ Mₙ*` if the message's last bytes `Mₙ*` are a complete block, and `Mₙ = K2 ⊕ (Mₙ* ‖ 10ʲ)` otherwise (step 4). The caller truncates it (step 7) and compares it (§6.3).
///
/// Contract: `VG.Spec.Cmac.aesFinishContract`. Constant time: only the pointers, `rounds` and `count` may affect timing, not the state.
///
/// This implementation calls the CMAC functions made with `vg_aes_ctr32_aesni` (e.g. `vg_cmac_aes_update_aesni`).
///
/// # Safety
///
/// * `state` must be valid for reads and writes of 304 bytes.
/// * `out` must be valid for reads and writes of 16 bytes.
/// * `scratch` must be valid for reads and writes of 2304 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `state` on return are unspecified.
/// * The contents of `scratch` on return are unspecified.
/// * `state`, `out` and `scratch` must not overlap each other or the arguments on the stack (distinct Rust objects never do).
/// * None of `state`, `out` and `scratch` may overlap the return address on the stack or the 56 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `aes` target feature.
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_cmac_aes_finish_aesni(state: *mut [u64; 38], rounds: usize, count: u64, out: *mut [u8; 16], scratch: *mut [u64; 288]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+24]",
        "mov DWORD PTR [eax+2176], ebx",
        "mov DWORD PTR [eax+2180], esi",
        "mov DWORD PTR [eax+2184], edi",
        "mov DWORD PTR [eax+2188], ebp",
        "mov esi, DWORD PTR [esp+4]",
        "add esi, 272",
        "mov edi, DWORD PTR [esp+20]",
        "mov ecx, 16",
        "test ecx, ecx",
        "je 20f",
        "22:",
        "movzx eax, BYTE PTR [esi]",
        "mov BYTE PTR [edi], al",
        "add esi, 1",
        "add edi, 1",
        "sub ecx, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov esi, DWORD PTR [esp+12]",
        "mov ecx, DWORD PTR [esp+16]",
        "or ecx, esi",
        "je 23f",
        "sub esi, 1",
        "and esi, 15",
        "add esi, 1",
        "jmp 24f",
        "23:",
        "24:",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov edx, DWORD PTR [esp+20]",
        "mov ebx, eax",
        "add ebx, 288",
        "mov edi, DWORD PTR [esp+24]",
        "push edi",
        "push esi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_cmac_aes_finalize_aesni}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [eax+2176]",
        "mov esi, DWORD PTR [eax+2180]",
        "mov edi, DWORD PTR [eax+2184]",
        "mov ebp, DWORD PTR [eax+2188]",
        "ret",
        ".p2align 6",
        vg_cmac_aes_finalize_aesni = sym super::cmac_aes::vg_cmac_aes_finalize_aesni,
    )
}

/// The CMAC subkey generation (NIST SP 800-38B §6.1) for AES: writes `K1 ‖ K2` to `*subkeys`, where `L = CIPH_K(0¹²⁸)`, `K1 = L << 1` (XORed with `R₁₂₈ = 0¹²⁰10000111` if the leftmost bit of `L` is 1) and `K2` is `K1` doubled the same way. `CIPH_K` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it.
///
/// Contract: `VG.Spec.Cmac.aesSubkeysContract`. Constant time: only the pointers and `rounds` may affect timing, not the key schedule or the subkeys.
///
/// This implementation encrypts each block with `vg_aes_ctr32`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `subkeys` must be valid for reads and writes of 32 bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `subkeys` and `scratch` must not overlap each other, `schedule` or the arguments on the stack (distinct Rust objects never do).
/// * None of `schedule`, `subkeys` and `scratch` may overlap the return address on the stack or the 28 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_cmac_aes_subkeys(schedule: *const [u8; 240], rounds: usize, subkeys: *mut [u8; 32], scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+16]",
        "mov DWORD PTR [eax+2064], ebx",
        "mov DWORD PTR [eax+2068], esi",
        "mov DWORD PTR [eax+2072], edi",
        "mov DWORD PTR [eax+2076], ebp",
        "mov ebp, eax",
        "mov ebx, DWORD PTR [esp+12]",
        "mov eax, 0",
        "mov DWORD PTR [ebp+2048], eax",
        "mov DWORD PTR [ebp+2052], eax",
        "mov DWORD PTR [ebp+2056], eax",
        "mov DWORD PTR [ebp+2060], eax",
        "mov eax, 0",
        "mov DWORD PTR [ebx], eax",
        "mov DWORD PTR [ebx+4], eax",
        "mov DWORD PTR [ebx+8], eax",
        "mov DWORD PTR [ebx+12], eax",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov edx, ebp",
        "add edx, 2048",
        "mov edi, 1",
        "push ebp",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_aes_ctr32}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [ebx]",
        "mov ecx, DWORD PTR [ebx+4]",
        "mov edx, DWORD PTR [ebx+8]",
        "mov esi, DWORD PTR [ebx+12]",
        "bswap eax",
        "bswap ecx",
        "bswap edx",
        "bswap esi",
        "mov edi, eax",
        "shr edi, 31",
        "mov ebp, 0",
        "sub ebp, edi",
        "and ebp, 135",
        "add eax, eax",
        "mov edi, ecx",
        "shr edi, 31",
        "or eax, edi",
        "add ecx, ecx",
        "mov edi, edx",
        "shr edi, 31",
        "or ecx, edi",
        "add edx, edx",
        "mov edi, esi",
        "shr edi, 31",
        "or edx, edi",
        "add esi, esi",
        "xor esi, ebp",
        "bswap eax",
        "bswap ecx",
        "bswap edx",
        "bswap esi",
        "mov DWORD PTR [ebx], eax",
        "mov DWORD PTR [ebx+4], ecx",
        "mov DWORD PTR [ebx+8], edx",
        "mov DWORD PTR [ebx+12], esi",
        "mov eax, DWORD PTR [ebx]",
        "mov ecx, DWORD PTR [ebx+4]",
        "mov edx, DWORD PTR [ebx+8]",
        "mov esi, DWORD PTR [ebx+12]",
        "bswap eax",
        "bswap ecx",
        "bswap edx",
        "bswap esi",
        "mov edi, eax",
        "shr edi, 31",
        "mov ebp, 0",
        "sub ebp, edi",
        "and ebp, 135",
        "add eax, eax",
        "mov edi, ecx",
        "shr edi, 31",
        "or eax, edi",
        "add ecx, ecx",
        "mov edi, edx",
        "shr edi, 31",
        "or ecx, edi",
        "add edx, edx",
        "mov edi, esi",
        "shr edi, 31",
        "or edx, edi",
        "add esi, esi",
        "xor esi, ebp",
        "bswap eax",
        "bswap ecx",
        "bswap edx",
        "bswap esi",
        "mov DWORD PTR [ebx+16], eax",
        "mov DWORD PTR [ebx+20], ecx",
        "mov DWORD PTR [ebx+24], edx",
        "mov DWORD PTR [ebx+28], esi",
        "mov eax, DWORD PTR [esp+16]",
        "mov ebx, DWORD PTR [eax+2064]",
        "mov esi, DWORD PTR [eax+2068]",
        "mov edi, DWORD PTR [eax+2072]",
        "mov ebp, DWORD PTR [eax+2076]",
        "ret",
        ".p2align 6",
        vg_aes_ctr32 = sym super::aes::vg_aes_ctr32,
    )
}

/// CMAC's chaining (NIST SP 800-38B §6.2 step 6) for AES, over whole blocks: replaces the block `C₀` at `*state` with `Cₙ`, where `Cᵢ = CIPH_K(Cᵢ₋₁ ⊕ Mᵢ)` for the `n` 16-byte blocks `M₁ … Mₙ` starting at `data`. `CIPH_K` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it.
///
/// Contract: `VG.Spec.Cmac.aesUpdateContract`. Constant time: only the pointers, `rounds` and `n` may affect timing, not the key schedule, the chaining value or the data.
///
/// This implementation encrypts each block with `vg_aes_ctr32`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `state` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `state` and `scratch` must not overlap each other, `schedule`, `data` or the arguments on the stack (distinct Rust objects never do).
/// * None of `schedule`, `state`, `data` and `scratch` may overlap the return address on the stack or the 28 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_cmac_aes_update(schedule: *const [u8; 240], rounds: usize, state: *mut [u8; 16], data: *const [u8; 16], n: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+24]",
        "mov DWORD PTR [eax+2064], ebx",
        "mov DWORD PTR [eax+2068], esi",
        "mov DWORD PTR [eax+2072], edi",
        "mov DWORD PTR [eax+2076], ebp",
        "mov esi, DWORD PTR [esp+16]",
        "mov eax, DWORD PTR [esp+20]",
        "test eax, eax",
        "je 20f",
        "22:",
        "mov ebx, DWORD PTR [esp+12]",
        "mov ebp, DWORD PTR [esp+24]",
        "mov eax, DWORD PTR [ebx]",
        "mov ecx, DWORD PTR [esi]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2048], eax",
        "mov eax, DWORD PTR [ebx+4]",
        "mov ecx, DWORD PTR [esi+4]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2052], eax",
        "mov eax, DWORD PTR [ebx+8]",
        "mov ecx, DWORD PTR [esi+8]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2056], eax",
        "mov eax, DWORD PTR [ebx+12]",
        "mov ecx, DWORD PTR [esi+12]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2060], eax",
        "mov eax, 0",
        "mov DWORD PTR [ebx], eax",
        "mov DWORD PTR [ebx+4], eax",
        "mov DWORD PTR [ebx+8], eax",
        "mov DWORD PTR [ebx+12], eax",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov edx, ebp",
        "add edx, 2048",
        "mov edi, 1",
        "push ebp",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_aes_ctr32}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "add esi, 16",
        "mov eax, DWORD PTR [esp+20]",
        "add eax, eax",
        "add eax, eax",
        "add eax, eax",
        "add eax, eax",
        "add eax, DWORD PTR [esp+16]",
        "cmp esi, eax",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov eax, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [eax+2064]",
        "mov esi, DWORD PTR [eax+2068]",
        "mov edi, DWORD PTR [eax+2072]",
        "mov ebp, DWORD PTR [eax+2076]",
        "ret",
        ".p2align 6",
        vg_aes_ctr32 = sym super::aes::vg_aes_ctr32,
    )
}

/// Finishes an AES-CMAC computation (NIST SP 800-38B §6.2, with `Tlen = 128`): if the block at `*state` is the chaining value `Cₙ₋₁` of the message's blocks but the last (as `vg_cmac_aes_update` computes it from a zero block), and the `last_len` bytes at `last` are the message's last bytes `Mₙ*`, replaces it with the MAC `Cₙ = CIPH_K(Cₙ₋₁ ⊕ Mₙ)`, where `Mₙ = K1 ⊕ Mₙ*` if `last_len` is 16, and `Mₙ = K2 ⊕ (Mₙ* ‖ 10ʲ)` otherwise. `*key` is the 240 bytes `vg_aes_expand_key` writes the key schedule for `rounds` rounds to, followed by the subkeys `K1 ‖ K2` (as `vg_cmac_aes_subkeys` writes them). `last_len` is 0 only for the empty message.
///
/// Contract: `VG.Spec.Cmac.aesFinalizeContract`. Constant time: only the pointers, `rounds` and `last_len` may affect timing, not the key schedule, the subkeys, the chaining value or the data.
///
/// This implementation encrypts each block with `vg_aes_ctr32`.
///
/// # Safety
///
/// * `key` must be valid for reads of 272 bytes.
/// * `state` must be valid for reads and writes of 16 bytes.
/// * `last` must be valid for reads of `last_len` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * `last_len` must be at most 16.
/// * The contents of `scratch` on return are unspecified.
/// * `state` and `scratch` must not overlap each other, `key`, `last` or the arguments on the stack (distinct Rust objects never do).
/// * None of `key`, `state`, `last` and `scratch` may overlap the return address on the stack or the 28 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_cmac_aes_finalize(key: *const [u8; 272], rounds: usize, state: *mut [u8; 16], last: *const u8, last_len: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+24]",
        "mov DWORD PTR [eax+2064], ebx",
        "mov DWORD PTR [eax+2068], esi",
        "mov DWORD PTR [eax+2072], edi",
        "mov DWORD PTR [eax+2076], ebp",
        "mov ebp, eax",
        "mov ecx, DWORD PTR [esp+20]",
        "cmp ecx, 16",
        "je 20f",
        "mov eax, 0",
        "mov DWORD PTR [ebp+2048], eax",
        "mov DWORD PTR [ebp+2052], eax",
        "mov DWORD PTR [ebp+2056], eax",
        "mov DWORD PTR [ebp+2060], eax",
        "mov edi, ebp",
        "add edi, 2048",
        "mov esi, DWORD PTR [esp+16]",
        "mov ecx, DWORD PTR [esp+20]",
        "test ecx, ecx",
        "je 22f",
        "24:",
        "movzx eax, BYTE PTR [esi]",
        "mov BYTE PTR [edi], al",
        "add esi, 1",
        "add edi, 1",
        "sub ecx, 1",
        "jne 24b",
        "jmp 23f",
        "22:",
        "23:",
        "mov eax, 128",
        "mov BYTE PTR [edi], al",
        "mov edx, DWORD PTR [esp+4]",
        "mov eax, DWORD PTR [ebp+2048]",
        "mov ecx, DWORD PTR [edx+256]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2048], eax",
        "mov eax, DWORD PTR [ebp+2052]",
        "mov ecx, DWORD PTR [edx+260]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2052], eax",
        "mov eax, DWORD PTR [ebp+2056]",
        "mov ecx, DWORD PTR [edx+264]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2056], eax",
        "mov eax, DWORD PTR [ebp+2060]",
        "mov ecx, DWORD PTR [edx+268]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2060], eax",
        "jmp 21f",
        "20:",
        "mov ebx, DWORD PTR [esp+16]",
        "mov edx, DWORD PTR [esp+4]",
        "mov eax, DWORD PTR [ebx]",
        "mov ecx, DWORD PTR [edx+240]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2048], eax",
        "mov eax, DWORD PTR [ebx+4]",
        "mov ecx, DWORD PTR [edx+244]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2052], eax",
        "mov eax, DWORD PTR [ebx+8]",
        "mov ecx, DWORD PTR [edx+248]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2056], eax",
        "mov eax, DWORD PTR [ebx+12]",
        "mov ecx, DWORD PTR [edx+252]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2060], eax",
        "21:",
        "mov ebx, DWORD PTR [esp+12]",
        "mov eax, DWORD PTR [ebp+2048]",
        "mov ecx, DWORD PTR [ebx]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2048], eax",
        "mov eax, DWORD PTR [ebp+2052]",
        "mov ecx, DWORD PTR [ebx+4]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2052], eax",
        "mov eax, DWORD PTR [ebp+2056]",
        "mov ecx, DWORD PTR [ebx+8]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2056], eax",
        "mov eax, DWORD PTR [ebp+2060]",
        "mov ecx, DWORD PTR [ebx+12]",
        "xor eax, ecx",
        "mov DWORD PTR [ebp+2060], eax",
        "mov eax, 0",
        "mov DWORD PTR [ebx], eax",
        "mov DWORD PTR [ebx+4], eax",
        "mov DWORD PTR [ebx+8], eax",
        "mov DWORD PTR [ebx+12], eax",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov edx, ebp",
        "add edx, 2048",
        "mov edi, 1",
        "push ebp",
        "push edi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_aes_ctr32}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [eax+2064]",
        "mov esi, DWORD PTR [eax+2068]",
        "mov edi, DWORD PTR [eax+2072]",
        "mov ebp, DWORD PTR [eax+2076]",
        "ret",
        ".p2align 6",
        vg_aes_ctr32 = sym super::aes::vg_aes_ctr32,
    )
}

/// Starts an AES-CMAC computation (NIST SP 800-38B, RFC 4493): makes the streaming state `*state` represent the empty message under the AES key of `key_len` bytes at `key` (AES-128, AES-192 or AES-256). The state holds the key schedule of AES (FIPS 197) with `key_len / 4 + 6` rounds, the subkeys `K1 ‖ K2` (§6.1), the chaining value and the message's last bytes, held back (`VG.Spec.Cmac.Repr`). Continue with `vg_cmac_aes_absorb` and `vg_cmac_aes_finish`, passing them `key_len / 4 + 6` as `rounds`.
///
/// Contract: `VG.Spec.Cmac.aesInitContract`. Constant time: only the pointers and `key_len` may affect timing, not the key.
///
/// This implementation calls the CMAC functions made with `vg_aes_ctr32` (e.g. `vg_cmac_aes_update`).
///
/// It expands the key with `vg_aes_expand_key`.
///
/// # Safety
///
/// * `state` must be valid for reads and writes of 304 bytes.
/// * `key` must be valid for reads of `key_len` bytes.
/// * `scratch` must be valid for reads and writes of 2304 bytes.
/// * `key_len` must be 16, 24 or 32.
/// * The contents of `scratch` on return are unspecified.
/// * `state` and `scratch` must not overlap each other, `key` or the arguments on the stack (distinct Rust objects never do).
/// * None of `state`, `key` and `scratch` may overlap the return address on the stack or the 48 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_cmac_aes_init(state: *mut [u64; 38], key: *const u8, key_len: usize, scratch: *mut [u64; 288]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+16]",
        "mov DWORD PTR [eax+2176], ebx",
        "mov DWORD PTR [eax+2180], esi",
        "mov DWORD PTR [eax+2184], edi",
        "mov DWORD PTR [eax+2188], ebp",
        "mov eax, DWORD PTR [esp+8]",
        "mov ecx, DWORD PTR [esp+12]",
        "mov edx, DWORD PTR [esp+4]",
        "mov ebx, DWORD PTR [esp+16]",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_aes_expand_key}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+12]",
        "shr ecx, 2",
        "add ecx, 6",
        "mov edx, eax",
        "add edx, 240",
        "mov ebx, DWORD PTR [esp+16]",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_cmac_aes_subkeys}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov edx, DWORD PTR [esp+4]",
        "mov eax, 0",
        "mov DWORD PTR [edx+272], eax",
        "mov DWORD PTR [edx+276], eax",
        "mov DWORD PTR [edx+280], eax",
        "mov DWORD PTR [edx+284], eax",
        "mov eax, DWORD PTR [esp+16]",
        "mov ebx, DWORD PTR [eax+2176]",
        "mov esi, DWORD PTR [eax+2180]",
        "mov edi, DWORD PTR [eax+2184]",
        "mov ebp, DWORD PTR [eax+2188]",
        "ret",
        ".p2align 6",
        vg_aes_expand_key = sym super::aes::vg_aes_expand_key,
        vg_cmac_aes_subkeys = sym super::cmac_aes::vg_cmac_aes_subkeys,
    )
}

/// Absorbs data into an AES-CMAC computation (NIST SP 800-38B §6.2): if the streaming state `*state` represents a message of `count` bytes under an AES key with `rounds` rounds (as `vg_cmac_aes_init` set it up), it then represents that message followed by the `len` bytes at `data`, under the same key, provided that the two together are shorter than 2⁶⁴ bytes. It chains (step 6) every block of the message but its last bytes `Mₙ*` (step 3), which it holds back in the state, since only `vg_cmac_aes_finish` knows they are the last.
///
/// Contract: `VG.Spec.Cmac.aesAbsorbContract`. Constant time: only the pointers, `rounds`, `count` and `len` may affect timing, not the state or the data.
///
/// This implementation calls the CMAC functions made with `vg_aes_ctr32` (e.g. `vg_cmac_aes_update`).
///
/// # Safety
///
/// * `state` must be valid for reads and writes of 304 bytes.
/// * `data` must be valid for reads of `len` bytes.
/// * `scratch` must be valid for reads and writes of 2304 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `state` and `scratch` must not overlap each other, `data` or the arguments on the stack (distinct Rust objects never do).
/// * None of `state`, `data` and `scratch` may overlap the return address on the stack or the 56 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_cmac_aes_absorb(state: *mut [u64; 38], rounds: usize, count: u64, data: *const u8, len: usize, scratch: *mut [u64; 288]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+28]",
        "mov DWORD PTR [eax+2176], ebx",
        "mov DWORD PTR [eax+2180], esi",
        "mov DWORD PTR [eax+2184], edi",
        "mov DWORD PTR [eax+2188], ebp",
        "mov eax, DWORD PTR [esp+12]",
        "mov ecx, DWORD PTR [esp+16]",
        "or ecx, eax",
        "je 20f",
        "sub eax, 1",
        "and eax, 15",
        "add eax, 1",
        "jmp 21f",
        "20:",
        "21:",
        "mov ecx, 16",
        "sub ecx, eax",
        "mov edx, DWORD PTR [esp+24]",
        "cmp edx, ecx",
        "jb 22f",
        "jmp 23f",
        "22:",
        "mov ecx, edx",
        "23:",
        "mov ebp, ecx",
        "mov esi, DWORD PTR [esp+20]",
        "mov edi, DWORD PTR [esp+4]",
        "add edi, 288",
        "add edi, eax",
        "test ecx, ecx",
        "je 24f",
        "26:",
        "movzx eax, BYTE PTR [esi]",
        "mov BYTE PTR [edi], al",
        "add esi, 1",
        "add edi, 1",
        "sub ecx, 1",
        "jne 26b",
        "jmp 25f",
        "24:",
        "25:",
        "mov esi, 0",
        "mov edx, DWORD PTR [esp+24]",
        "sub edx, ebp",
        "je 27f",
        "mov esi, 1",
        "jmp 28f",
        "27:",
        "28:",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov edx, eax",
        "add edx, 272",
        "mov ebx, eax",
        "add ebx, 288",
        "mov edi, DWORD PTR [esp+28]",
        "push edi",
        "push esi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_cmac_aes_update}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov ecx, 0",
        "mov ebx, DWORD PTR [esp+4]",
        "add ebx, 288",
        "mov edx, DWORD PTR [esp+24]",
        "sub edx, ebp",
        "je 29f",
        "mov ecx, edx",
        "sub ecx, 1",
        "mov eax, ecx",
        "and eax, 15",
        "sub ecx, eax",
        "mov ebx, DWORD PTR [esp+20]",
        "add ebx, ebp",
        "jmp 210f",
        "29:",
        "210:",
        "mov esi, ecx",
        "shr esi, 4",
        "add ebp, ecx",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov edx, eax",
        "add edx, 272",
        "mov edi, DWORD PTR [esp+28]",
        "push edi",
        "push esi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_cmac_aes_update}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov esi, DWORD PTR [esp+20]",
        "add esi, ebp",
        "mov edi, DWORD PTR [esp+4]",
        "add edi, 288",
        "mov ecx, DWORD PTR [esp+24]",
        "sub ecx, ebp",
        "test ecx, ecx",
        "je 211f",
        "213:",
        "movzx eax, BYTE PTR [esi]",
        "mov BYTE PTR [edi], al",
        "add esi, 1",
        "add edi, 1",
        "sub ecx, 1",
        "jne 213b",
        "jmp 212f",
        "211:",
        "212:",
        "mov eax, DWORD PTR [esp+28]",
        "mov ebx, DWORD PTR [eax+2176]",
        "mov esi, DWORD PTR [eax+2180]",
        "mov edi, DWORD PTR [eax+2184]",
        "mov ebp, DWORD PTR [eax+2188]",
        "ret",
        ".p2align 6",
        vg_cmac_aes_update = sym super::cmac_aes::vg_cmac_aes_update,
    )
}

/// Finishes an AES-CMAC computation (NIST SP 800-38B §6.2, with `Tlen = 128`): if the streaming state `*state` represents a message of `count` bytes, shorter than 2⁶⁴ bytes, under an AES key with `rounds` rounds (as `vg_cmac_aes_init` and `vg_cmac_aes_absorb` set it up), writes the MAC of that message under that key to `*out`: `Cₙ = CIPH_K(Cₙ₋₁ ⊕ Mₙ)`, where `Mₙ = K1 ⊕ Mₙ*` if the message's last bytes `Mₙ*` are a complete block, and `Mₙ = K2 ⊕ (Mₙ* ‖ 10ʲ)` otherwise (step 4). The caller truncates it (step 7) and compares it (§6.3).
///
/// Contract: `VG.Spec.Cmac.aesFinishContract`. Constant time: only the pointers, `rounds` and `count` may affect timing, not the state.
///
/// This implementation calls the CMAC functions made with `vg_aes_ctr32` (e.g. `vg_cmac_aes_update`).
///
/// # Safety
///
/// * `state` must be valid for reads and writes of 304 bytes.
/// * `out` must be valid for reads and writes of 16 bytes.
/// * `scratch` must be valid for reads and writes of 2304 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `state` on return are unspecified.
/// * The contents of `scratch` on return are unspecified.
/// * `state`, `out` and `scratch` must not overlap each other or the arguments on the stack (distinct Rust objects never do).
/// * None of `state`, `out` and `scratch` may overlap the return address on the stack or the 56 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_cmac_aes_finish(state: *mut [u64; 38], rounds: usize, count: u64, out: *mut [u8; 16], scratch: *mut [u64; 288]) {
    core::arch::naked_asm!(
        "mov eax, DWORD PTR [esp+24]",
        "mov DWORD PTR [eax+2176], ebx",
        "mov DWORD PTR [eax+2180], esi",
        "mov DWORD PTR [eax+2184], edi",
        "mov DWORD PTR [eax+2188], ebp",
        "mov esi, DWORD PTR [esp+4]",
        "add esi, 272",
        "mov edi, DWORD PTR [esp+20]",
        "mov ecx, 16",
        "test ecx, ecx",
        "je 20f",
        "22:",
        "movzx eax, BYTE PTR [esi]",
        "mov BYTE PTR [edi], al",
        "add esi, 1",
        "add edi, 1",
        "sub ecx, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov esi, DWORD PTR [esp+12]",
        "mov ecx, DWORD PTR [esp+16]",
        "or ecx, esi",
        "je 23f",
        "sub esi, 1",
        "and esi, 15",
        "add esi, 1",
        "jmp 24f",
        "23:",
        "24:",
        "mov eax, DWORD PTR [esp+4]",
        "mov ecx, DWORD PTR [esp+8]",
        "mov edx, DWORD PTR [esp+20]",
        "mov ebx, eax",
        "add ebx, 288",
        "mov edi, DWORD PTR [esp+24]",
        "push edi",
        "push esi",
        "push ebx",
        "push edx",
        "push ecx",
        "push eax",
        "call {vg_cmac_aes_finalize}",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "pop eax",
        "mov eax, DWORD PTR [esp+24]",
        "mov ebx, DWORD PTR [eax+2176]",
        "mov esi, DWORD PTR [eax+2180]",
        "mov edi, DWORD PTR [eax+2184]",
        "mov ebp, DWORD PTR [eax+2188]",
        "ret",
        ".p2align 6",
        vg_cmac_aes_finalize = sym super::cmac_aes::vg_cmac_aes_finalize,
    )
}
