//! Hash functions, one module each (see each module for its standard and
//! the architectures it supports).
//!
//! Each one's whole computation is verified assembly: an `init`, `update` and
//! `finalize` that maintain a streaming state representing the message
//! absorbed so far, and pad it and output the digest (see each module). The
//! Rust types, generated by `streaming_hash!`, only keep that state together
//! with the message length, which the contracts take as an argument. (SHA-3
//! and SHAKE instead absorb, pad and squeeze a Keccak state, together with
//! the position in the current block: see `sha3`.)

#![cfg(any(
    target_arch = "x86_64",
    target_arch = "aarch64",
    target_arch = "arm",
    target_arch = "x86"
))]

mod blake2;
pub mod blake2b;
pub mod blake2s;
pub mod md5;
pub mod sha1;
pub mod sha224;
pub mod sha256;
pub mod sha3;
pub mod sha384;
pub mod sha512;
pub mod sha512_224;
pub mod sha512_256;

/// A hash function with an incremental interface, as used by the
/// constructions that are generic over it (HMAC).
pub trait HashFunction: Clone {
    /// The size of a digest, in bytes.
    const OUTPUT_SIZE: usize;
    /// The size of the input blocks, in bytes (the `B` of HMAC).
    const BLOCK_SIZE: usize;
    /// A digest: `OUTPUT_SIZE` bytes.
    type Output: AsRef<[u8]> + AsMut<[u8]> + Clone;

    /// Starts a new computation.
    fn new() -> Self;
    /// Absorbs `data`.
    fn update(&mut self, data: &[u8]);
    /// Returns the digest of everything absorbed.
    fn finalize(self) -> Self::Output;

    /// The digest of `data`.
    fn digest(data: &[u8]) -> Self::Output {
        let mut h = Self::new();
        h.update(data);
        h.finalize()
    }
}

/// Defines a hash function over verified streaming primitives:
///
/// * `init(state: *mut [u8; STATE])` makes `state` represent the empty
///   message;
/// * `update(state, count: u64, data: *const u8, len: usize, scratch: *mut [u64; SCRATCH])`
///   absorbs `len` bytes into a state representing a message of `count`
///   bytes;
/// * `finalize(state, count: u64, out: *mut [u8; FINAL], scratch)` writes
///   the final hash value, whose first `OUTPUT` bytes are the digest.
///
/// `backends` names the enum of the implementations of `update` and
/// `finalize` to choose from, each a variant: first the one for the
/// target's baseline ISA, then any that need CPU features (their generated
/// `_FEATURES` constants), best first. An object uses the first
/// that the CPU can run, chosen when it is created (see `crate::cpu`).
///
/// Every region is a distinct Rust object, so none overlaps another or the
/// return address, and none wraps around the end of the address space; the
/// length is kept exactly (`update` panics rather than let it reach 2⁶⁴
/// bytes).
macro_rules! streaming_hash {
    (
        $(#[$doc:meta])*
        $name:ident {
            state: $state:literal,
            scratch: $scratch:literal,
            block: $block:literal,
            output: $output:literal,
            final_hash: $final:literal,
            init: $init:path,
            backends: $backend:ident {
                $base:ident => ($update:path, $finalize:path)
                $(, $(#[$attr:meta])* $variant:ident if [$($req:path),*] => ($vupdate:path, $vfinalize:path))*
                $(,)?
            } $(,)?
        }
    ) => {
        /// The implementations of the streaming primitives.
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub(crate) enum $backend {
            /// For the baseline ISA.
            $base,
            $(
                $(#[$attr])*
                /// Needing CPU features.
                $variant,
            )*
        }

        impl $backend {
            /// The best implementation a CPU with the features `f` can run.
            pub(crate) fn select(f: $crate::cpu::Features) -> Self {
                $(
                    $(#[$attr])*
                    if f.contains(const { $crate::cpu::Features::all(&[$($req),*]) }) {
                        return Self::$variant;
                    }
                )*
                let _ = f;
                Self::$base
            }

            /// `update`.
            ///
            /// # Safety
            ///
            /// As for the artifacts; the CPU must have the features of the
            /// implementation (as `select` guarantees).
            pub(crate) unsafe fn update(
                self,
                state: &mut [u8; $state],
                count: u64,
                data: *const u8,
                len: usize,
                scratch: &mut [u64; $scratch],
            ) {
                // SAFETY: the caller's obligations.
                unsafe {
                    match self {
                        Self::$base => $update(state, count, data, len, scratch),
                        $($(#[$attr])* Self::$variant => $vupdate(state, count, data, len, scratch),)*
                    }
                }
            }

            /// `finalize`.
            ///
            /// # Safety
            ///
            /// As for the artifacts; the CPU must have the features of the
            /// implementation (as `select` guarantees).
            pub(crate) unsafe fn finalize(
                self,
                state: &mut [u8; $state],
                count: u64,
                out: &mut [u8; $final],
                scratch: &mut [u64; $scratch],
            ) {
                // SAFETY: the caller's obligations.
                unsafe {
                    match self {
                        Self::$base => $finalize(state, count, out, scratch),
                        $($(#[$attr])* Self::$variant => $vfinalize(state, count, out, scratch),)*
                    }
                }
            }
        }

        $(#[$doc])*
        ///
        /// Messages are limited to 2⁶⁴ − 1 bytes.
        #[derive(Clone)]
        pub struct $name {
            /// The streaming state, representing the message so far.
            state: [u8; $state],
            /// The message length so far, in bytes.
            length: u64,
            /// The implementation this CPU runs.
            backend: $backend,
        }

        impl Default for $name {
            fn default() -> Self {
                Self::new()
            }
        }

        impl Drop for $name {
            /// Wipes the streaming state (which, for HMAC, represents the
            /// key).
            fn drop(&mut self) {
                $crate::zeroize::zeroize(&mut self.state);
            }
        }

        impl $name {
            /// The size of a digest, in bytes.
            pub const OUTPUT_SIZE: usize = $output;
            /// The size of a message block, in bytes.
            pub const BLOCK_SIZE: usize = $block;

            /// Starts a new computation.
            pub fn new() -> Self {
                let mut state = [0; $state];
                // SAFETY: `state` is valid for writes of its size, and is a
                // distinct object from the return address (on x86-64 and x86)
                // and the argument on the stack (on x86); as a Rust object, it
                // does not wrap around the end of the address space.
                unsafe { $init(&mut state) };
                let backend = $backend::select($crate::cpu::detected());
                $name { state, length: 0, backend }
            }

            /// Absorbs `data`.
            ///
            /// # Panics
            ///
            /// If the message reaches 2⁶⁴ bytes.
            pub fn update(&mut self, data: &[u8]) {
                let length = self
                    .length
                    .checked_add(data.len() as u64)
                    .expect("message too long");
                let mut scratch = [0u64; $scratch];
                // SAFETY: `self.state` is valid for reads and writes of its
                // size, `data` for reads of `data.len()` bytes and `scratch`
                // for reads and writes of its size; they are distinct
                // objects, so they do not overlap each other, the return
                // address (on x86-64 and x86) or the arguments on the stack
                // (on 32-bit ARM and x86), and do not wrap around the end of
                // the address space. `self.length` is the length of the
                // message `self.state` represents. `self.backend` was
                // selected for this CPU's features.
                unsafe {
                    self.backend.update(
                        &mut self.state,
                        self.length,
                        data.as_ptr(),
                        data.len(),
                        &mut scratch,
                    )
                };
                self.length = length;
            }

            /// Pads the message and returns its digest.
            pub fn finalize(mut self) -> [u8; $output] {
                let mut out = [0; $final];
                let mut scratch = [0u64; $scratch];
                // SAFETY: `self.state` is valid for reads and writes of its
                // size, `out` for writes of its size and `scratch` for reads
                // and writes of its size; they are distinct objects, so they
                // do not overlap each other, the return address (on x86-64
                // and x86) or the arguments on the stack (on 32-bit ARM and
                // x86), and do not wrap around the end of the address space.
                // `self.length` is the exact length of the message
                // `self.state` represents. `self.backend` was selected for
                // this CPU's features.
                unsafe {
                    self.backend
                        .finalize(&mut self.state, self.length, &mut out, &mut scratch)
                };
                let mut digest = [0; $output];
                digest.copy_from_slice(&out[..$output]);
                digest
            }

            /// The digest of `data`.
            pub fn digest(data: &[u8]) -> [u8; $output] {
                let mut h = Self::new();
                h.update(data);
                h.finalize()
            }

            /// A computation whose streaming state is `state`, which must
            /// represent a message of `length` bytes (for HMAC, whose
            /// `init` makes such states), and which runs the implementation
            /// `backend` (which must have been selected for this CPU).
            #[cfg(any(target_arch = "x86_64", target_arch = "aarch64", target_arch = "arm", target_arch = "x86"))]
            #[allow(dead_code)]
            pub(crate) fn from_state(state: [u8; $state], length: u64, backend: $backend) -> Self {
                $name { state, length, backend }
            }

            /// The implementation this computation runs, selected for this
            /// CPU, which functions built on it (e.g. HMAC's) follow.
            #[cfg(any(target_arch = "x86_64", target_arch = "aarch64", target_arch = "arm", target_arch = "x86"))]
            #[allow(dead_code)]
            pub(crate) fn backend(&self) -> $backend {
                self.backend
            }

            /// The streaming state, in place, and the length of the message
            /// it represents.
            #[cfg(any(target_arch = "x86_64", target_arch = "aarch64", target_arch = "arm", target_arch = "x86"))]
            #[allow(dead_code)]
            pub(crate) fn state_mut(&mut self) -> (&mut [u8; $state], u64) {
                (&mut self.state, self.length)
            }
        }

        impl $crate::hashes::HashFunction for $name {
            const OUTPUT_SIZE: usize = $name::OUTPUT_SIZE;
            const BLOCK_SIZE: usize = $name::BLOCK_SIZE;
            type Output = [u8; $output];

            fn new() -> Self {
                $name::new()
            }

            fn update(&mut self, data: &[u8]) {
                $name::update(self, data)
            }

            fn finalize(self) -> [u8; $output] {
                $name::finalize(self)
            }
        }
    };
}

use streaming_hash;
