name = "ECDSA P-192"
family = "Signatures"
specs = ["Weierstrass", "P192", "EcKey", "Ecdsa", "Ecdsa/Rfc6979", "Ecdsa/Verify"]
modules = ["src/ecdsa/p192.rs"]
asm = ["ec_p192", "ecdsa_p192", "ecdsa_p192_sha256"]
