name = "ECDSA P-224"
family = "Signatures"
specs = ["Weierstrass", "P224", "EcKey", "Ecdsa", "Ecdsa/Rfc6979", "Ecdsa/Verify"]
modules = ["src/ecdsa/p224.rs"]
asm = ["ec_p224", "ecdsa_p224", "ecdsa_p224_sha224", "p224_mont"]
