import VerifiedGarbage.TCB.Emit

/-!
# Golden tests for the emitter's driver

`Emit.driver` writes the program that emits every artifact: these tests pin
down which modules it imports and how it applies each generic function to
each variant of its interface and target.
-/

namespace VG.Test.Emit

open VG.Emit

#guard groupOf "VerifiedGarbage.Variants.Sha256Compress.X86_64.ShaNi" == some "Sha256Compress.X86_64"
#guard groupOf "VerifiedGarbage.Variants.Sha256Compress.ShaNi" == none
#guard groupOf "VerifiedGarbage.Variants.Sha256Compress.X86_64.Sub.ShaNi" == none

#guard interfacesOf "VerifiedGarbage.Generic.Sha256Compress.X86_64.Pbkdf2" ==
  some ["Sha256Compress.X86_64"]
#guard interfacesOf "VerifiedGarbage.Generic.Blake2b.Argon2Compress.X86_64.Argon2" ==
  some ["Blake2b.X86_64", "Argon2Compress.X86_64"]
#guard interfacesOf "VerifiedGarbage.Generic.X86_64.Pbkdf2" == none
#guard interfacesOf "VerifiedGarbage.Generic.Pbkdf2" == none

#guard variantOf "VerifiedGarbage.Variants.Sha256Compress.X86_64.ShaNi" ==
  "VG.Variants.Sha256Compress.X86_64.ShaNi.variant"

-- Instances of a caller of several interfaces: one qualified part per
-- interface whose variant has a suffix; the baseline instance keeps the name.
#guard qualifiedName "vg_argon2" [("blake2b", ""), ("g", "")] == "vg_argon2"
#guard qualifiedName "vg_argon2" [("blake2b", ""), ("g", "_avx512")] ==
  "vg_argon2_g_avx512"
#guard qualifiedName "vg_argon2" [("blake2b", "_avx2"), ("g", "_avx512")] ==
  "vg_argon2_blake2b_avx2_g_avx512"
-- The same suffix in different interfaces gives different names.
#guard qualifiedName "vg_argon2" [("blake2b", "_avx2"), ("g", "")] ==
  "vg_argon2_blake2b_avx2"
#guard qualifiedName "vg_argon2" [("blake2b", ""), ("g", "_avx2")] ==
  "vg_argon2_g_avx2"
#guard qualifiedName "vg_argon2" [("blake2b", "_avx2"), ("g", "_avx2")] ==
  "vg_argon2_blake2b_avx2_g_avx2"

-- Without variants or generic files, the driver is what it was.
#guard driver ["VerifiedGarbage.Artifacts.Sha3.X86_64"] ==
  "-- Generated by Emit.lean, which runs it. DO NOT EDIT.\n\
  import VerifiedGarbage.TCB.Audit\n\
  import VerifiedGarbage.TCB.Axioms\n\
  import VerifiedGarbage.TCB.Emit\n\
  import VerifiedGarbage.Artifacts\n\
  import VerifiedGarbage.Artifacts.Sha3.X86_64\n\
  \n\
  namespace VG.Emit\n\
  \n\
  def all : List Artifact := List.flatten [\n  \
    VG.Artifacts.Sha3.X86_64.artifacts,\n  \
    VG.artifacts]\n\
  \n\
  #assert_standard_axioms all\n\
  #assert_no_compiler_overrides all run\n\
  #assert_spec_origin\n\
  \n\
  end VG.Emit\n\
  \n\
  def main (args : List String) : IO UInt32 := VG.Emit.run VG.Emit.all args\n"

-- Each generic function of an interface is applied to each of its
-- variants; variants of an interface without generic functions add nothing.
#guard driver ["VerifiedGarbage.Artifacts.Sha256.X86_64"]
    [(["I.X86_64"], ["VerifiedGarbage.Generic.I.X86_64.A", "VerifiedGarbage.Generic.I.X86_64.B"])]
    [("I.X86_64", ["VerifiedGarbage.Variants.I.X86_64.P", "VerifiedGarbage.Variants.I.X86_64.Q"]),
     ("J.X86_64", ["VerifiedGarbage.Variants.J.X86_64.R"])] ==
  "-- Generated by Emit.lean, which runs it. DO NOT EDIT.\n\
  import VerifiedGarbage.TCB.Audit\n\
  import VerifiedGarbage.TCB.Axioms\n\
  import VerifiedGarbage.TCB.Emit\n\
  import VerifiedGarbage.Artifacts\n\
  import VerifiedGarbage.Artifacts.Sha256.X86_64\n\
  import VerifiedGarbage.Generic.I.X86_64.A\n\
  import VerifiedGarbage.Generic.I.X86_64.B\n\
  import VerifiedGarbage.Variants.I.X86_64.P\n\
  import VerifiedGarbage.Variants.I.X86_64.Q\n\
  import VerifiedGarbage.Variants.J.X86_64.R\n\
  \n\
  namespace VG.Emit\n\
  \n\
  def all : List Artifact := List.flatten [\n  \
    VG.Artifacts.Sha256.X86_64.artifacts,\n  \
    (List.flatMap (fun v => List.flatten [VG.Generic.I.X86_64.A.artifacts v, \
      VG.Generic.I.X86_64.B.artifacts v]) \
      [VG.Variants.I.X86_64.P.variant, VG.Variants.I.X86_64.Q.variant]),\n  \
    VG.artifacts]\n\
  \n\
  #assert_standard_axioms all\n\
  #assert_no_compiler_overrides all run\n\
  #assert_spec_origin\n\
  \n\
  end VG.Emit\n\
  \n\
  def main (args : List String) : IO UInt32 := VG.Emit.run VG.Emit.all args\n"

-- A generic function of two interfaces is applied to each pair of a variant
-- of the first and a variant of the second, the first varying slowest.
#guard driver []
    [(["I.X86_64", "J.X86_64"], ["VerifiedGarbage.Generic.I.J.X86_64.A"])]
    [("I.X86_64", ["VerifiedGarbage.Variants.I.X86_64.P", "VerifiedGarbage.Variants.I.X86_64.Q"]),
     ("J.X86_64", ["VerifiedGarbage.Variants.J.X86_64.R", "VerifiedGarbage.Variants.J.X86_64.S"])] ==
  "-- Generated by Emit.lean, which runs it. DO NOT EDIT.\n\
  import VerifiedGarbage.TCB.Audit\n\
  import VerifiedGarbage.TCB.Axioms\n\
  import VerifiedGarbage.TCB.Emit\n\
  import VerifiedGarbage.Artifacts\n\
  import VerifiedGarbage.Generic.I.J.X86_64.A\n\
  import VerifiedGarbage.Variants.I.X86_64.P\n\
  import VerifiedGarbage.Variants.I.X86_64.Q\n\
  import VerifiedGarbage.Variants.J.X86_64.R\n\
  import VerifiedGarbage.Variants.J.X86_64.S\n\
  \n\
  namespace VG.Emit\n\
  \n\
  def all : List Artifact := List.flatten [\n  \
    (List.flatMap (fun v => (List.flatMap (fun v2 => \
      List.flatten [VG.Generic.I.J.X86_64.A.artifacts v v2]) \
      [VG.Variants.J.X86_64.R.variant, VG.Variants.J.X86_64.S.variant])) \
      [VG.Variants.I.X86_64.P.variant, VG.Variants.I.X86_64.Q.variant]),\n  \
    VG.artifacts]\n\
  \n\
  #assert_standard_axioms all\n\
  #assert_no_compiler_overrides all run\n\
  #assert_spec_origin\n\
  \n\
  end VG.Emit\n\
  \n\
  def main (args : List String) : IO UInt32 := VG.Emit.run VG.Emit.all args\n"

end VG.Test.Emit
