// @generated by lean/Emit.lean. DO NOT EDIT.
//! Verified `aes_ctr` functions for `aarch64`.
#![allow(dead_code)]

/// The CPU features `vg_aes_ctr_aes` requires (`Artifact.features`).
pub(crate) const VG_AES_CTR_AES_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["aes"]);

/// AES-CTR encryption or decryption (NIST SP 800-38A §6.5) of whole blocks, in place: XORs the `n` 16-byte blocks at `data` with the output blocks `Oⱼ = CIPH_K(Tⱼ)`, where `T₁` is the block at `*ctr` and `Tⱼ₊₁ = Tⱼ + 1 mod 2¹²⁸` (Appendix B.1's standard incrementing function on the whole block, read as a big-endian integer), and replaces `*ctr` with `Tₙ₊₁` (leaving it unchanged if `n = 0`), so that a further call continues the message. `CIPH_K` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it.
///
/// Contract: `VG.Spec.Ctr.aesContract`. Constant time: only the pointers, `rounds`, `n` and the last four bytes of `*ctr` (the 32-bit counter, public in OpenSSL, BoringSSL and AWS-LC, which split the blocks where it wraps) may affect timing, not the key schedule, the rest of the counter block or the data.
///
/// This implementation enciphers one block at a time with `vg_aes_encrypt_blocks_aes`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `ctr` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `ctr`, `data` and `scratch` must not overlap each other or `schedule` (distinct Rust objects never do).
/// * None of `schedule`, `ctr`, `data` and `scratch` may wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `aes` target feature.
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_aes_ctr_aes(schedule: *const [u8; 240], rounds: usize, ctr: *mut [u8; 16], data: *mut [u8; 16], n: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        ".arch_extension aes",
        "str x19, [x5, #2064]",
        "str x20, [x5, #2072]",
        "str x21, [x5, #2080]",
        "str x22, [x5, #2088]",
        "str x23, [x5, #2096]",
        "str x30, [x5, #2104]",
        "str x24, [x5, #2112]",
        "add x19, x0, #0",
        "add x20, x1, #0",
        "add x21, x2, #0",
        "add x22, x3, #0",
        "add x23, x4, #0",
        "add x24, x5, #0",
        "cbz x23, 20f",
        "22:",
        "ldr x9, [x21, #0]",
        "str x9, [x24, #2048]",
        "ldr x9, [x21, #8]",
        "str x9, [x24, #2056]",
        "add x0, x19, #0",
        "add x1, x20, #0",
        "add x2, x24, #2048",
        "movz x3, #1, lsl #0",
        "add x4, x24, #0",
        "bl {vg_aes_encrypt_blocks_aes}",
        "ldr x9, [x22, #0]",
        "ldr x10, [x24, #2048]",
        "eor x9, x9, x10",
        "str x9, [x22, #0]",
        "ldr x9, [x22, #8]",
        "ldr x10, [x24, #2056]",
        "eor x9, x9, x10",
        "str x9, [x22, #8]",
        "ldr x9, [x21, #8]",
        "rev x9, x9",
        "ldr x10, [x21, #0]",
        "rev x10, x10",
        "movz x11, #1, lsl #0",
        "movz x12, #0, lsl #0",
        "adds x9, x9, x11",
        "adc x10, x10, x12",
        "rev x9, x9",
        "rev x10, x10",
        "str x9, [x21, #8]",
        "str x10, [x21, #0]",
        "add x22, x22, #16",
        "sub x23, x23, #1",
        "cbnz x23, 22b",
        "b 21f",
        "20:",
        "21:",
        "ldr x19, [x24, #2064]",
        "ldr x20, [x24, #2072]",
        "ldr x21, [x24, #2080]",
        "ldr x22, [x24, #2088]",
        "ldr x23, [x24, #2096]",
        "ldr x30, [x24, #2104]",
        "ldr x24, [x24, #2112]",
        "ret",
        ".arch_extension noaes",
        ".p2align 6",
        vg_aes_encrypt_blocks_aes = sym super::aes::vg_aes_encrypt_blocks_aes,
    )
}

/// AES-CTR encryption or decryption (NIST SP 800-38A §6.5) of whole blocks, in place: XORs the `n` 16-byte blocks at `data` with the output blocks `Oⱼ = CIPH_K(Tⱼ)`, where `T₁` is the block at `*ctr` and `Tⱼ₊₁ = Tⱼ + 1 mod 2¹²⁸` (Appendix B.1's standard incrementing function on the whole block, read as a big-endian integer), and replaces `*ctr` with `Tₙ₊₁` (leaving it unchanged if `n = 0`), so that a further call continues the message. `CIPH_K` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it.
///
/// Contract: `VG.Spec.Ctr.aesContract`. Constant time: only the pointers, `rounds`, `n` and the last four bytes of `*ctr` (the 32-bit counter, public in OpenSSL, BoringSSL and AWS-LC, which split the blocks where it wraps) may affect timing, not the key schedule, the rest of the counter block or the data.
///
/// This implementation enciphers one block at a time with `vg_aes_encrypt_blocks`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `ctr` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `ctr`, `data` and `scratch` must not overlap each other or `schedule` (distinct Rust objects never do).
/// * None of `schedule`, `ctr`, `data` and `scratch` may wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_aes_ctr(schedule: *const [u8; 240], rounds: usize, ctr: *mut [u8; 16], data: *mut [u8; 16], n: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "str x19, [x5, #2064]",
        "str x20, [x5, #2072]",
        "str x21, [x5, #2080]",
        "str x22, [x5, #2088]",
        "str x23, [x5, #2096]",
        "str x30, [x5, #2104]",
        "str x24, [x5, #2112]",
        "add x19, x0, #0",
        "add x20, x1, #0",
        "add x21, x2, #0",
        "add x22, x3, #0",
        "add x23, x4, #0",
        "add x24, x5, #0",
        "cbz x23, 20f",
        "22:",
        "ldr x9, [x21, #0]",
        "str x9, [x24, #2048]",
        "ldr x9, [x21, #8]",
        "str x9, [x24, #2056]",
        "add x0, x19, #0",
        "add x1, x20, #0",
        "add x2, x24, #2048",
        "movz x3, #1, lsl #0",
        "add x4, x24, #0",
        "bl {vg_aes_encrypt_blocks}",
        "ldr x9, [x22, #0]",
        "ldr x10, [x24, #2048]",
        "eor x9, x9, x10",
        "str x9, [x22, #0]",
        "ldr x9, [x22, #8]",
        "ldr x10, [x24, #2056]",
        "eor x9, x9, x10",
        "str x9, [x22, #8]",
        "ldr x9, [x21, #8]",
        "rev x9, x9",
        "ldr x10, [x21, #0]",
        "rev x10, x10",
        "movz x11, #1, lsl #0",
        "movz x12, #0, lsl #0",
        "adds x9, x9, x11",
        "adc x10, x10, x12",
        "rev x9, x9",
        "rev x10, x10",
        "str x9, [x21, #8]",
        "str x10, [x21, #0]",
        "add x22, x22, #16",
        "sub x23, x23, #1",
        "cbnz x23, 22b",
        "b 21f",
        "20:",
        "21:",
        "ldr x19, [x24, #2064]",
        "ldr x20, [x24, #2072]",
        "ldr x21, [x24, #2080]",
        "ldr x22, [x24, #2088]",
        "ldr x23, [x24, #2096]",
        "ldr x30, [x24, #2104]",
        "ldr x24, [x24, #2112]",
        "ret",
        ".p2align 6",
        vg_aes_encrypt_blocks = sym super::aes::vg_aes_encrypt_blocks,
    )
}
