// @generated by lean/Emit.lean. DO NOT EDIT.
//! Verified `aes_cfb8` functions for `aarch64`.
#![allow(dead_code)]

/// The CPU features `vg_aes_cfb8_encrypt_aes` requires (`Artifact.features`).
pub(crate) const VG_AES_CFB8_ENCRYPT_AES_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["aes"]);

/// AES-CFB8 encryption (NIST SP 800-38A §6.3, with 8-bit segments), in place: replaces the `len` bytes `P#₁ … P#ₙ` at `data` with `C#ⱼ = P#ⱼ ⊕ MSB₈(CIPH_K(Iⱼ))`, where `I₁` is the block at `*iv` and `Iⱼ₊₁` is `Iⱼ` without its first byte, followed by `C#ⱼ`, and `*iv` with `Iₙ₊₁` (leaving it unchanged if `len = 0`), so that a further call continues the message. `CIPH_K` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it.
///
/// Contract: `VG.Spec.Cfb8.aesEncryptContract`. Constant time: only the pointers, `rounds` and `len` may affect timing, not the key schedule, the input block or the data.
///
/// This implementation enciphers one block for each byte with `vg_aes_encrypt_blocks_aes`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `iv` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `len` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `iv`, `data` and `scratch` must not overlap each other or `schedule` (distinct Rust objects never do).
/// * None of `schedule`, `iv`, `data` and `scratch` may wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `aes` target feature.
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_aes_cfb8_encrypt_aes(schedule: *const [u8; 240], rounds: usize, iv: *mut [u8; 16], data: *mut u8, len: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        ".arch_extension aes",
        "str x19, [x5, #2064]",
        "str x20, [x5, #2072]",
        "str x21, [x5, #2080]",
        "str x22, [x5, #2088]",
        "str x23, [x5, #2096]",
        "str x30, [x5, #2104]",
        "str x24, [x5, #2112]",
        "add x19, x0, #0",
        "add x20, x1, #0",
        "add x21, x2, #0",
        "add x22, x3, #0",
        "add x23, x4, #0",
        "add x24, x5, #0",
        "cbz x23, 20f",
        "22:",
        "ldr x9, [x21, #0]",
        "str x9, [x24, #2048]",
        "ldr x9, [x21, #8]",
        "str x9, [x24, #2056]",
        "add x0, x19, #0",
        "add x1, x20, #0",
        "add x2, x24, #2048",
        "movz x3, #1, lsl #0",
        "add x4, x24, #0",
        "bl {vg_aes_encrypt_blocks_aes}",
        "ldrb w9, [x22, #0]",
        "ldrb w10, [x24, #2048]",
        "eor x9, x9, x10",
        "strb w9, [x22, #0]",
        "ldr x10, [x21, #0]",
        "ldr x11, [x21, #8]",
        "extr x12, x11, x10, #8",
        "extr x13, x9, x11, #8",
        "str x12, [x21, #0]",
        "str x13, [x21, #8]",
        "add x22, x22, #1",
        "sub x23, x23, #1",
        "cbnz x23, 22b",
        "b 21f",
        "20:",
        "21:",
        "ldr x19, [x24, #2064]",
        "ldr x20, [x24, #2072]",
        "ldr x21, [x24, #2080]",
        "ldr x22, [x24, #2088]",
        "ldr x23, [x24, #2096]",
        "ldr x30, [x24, #2104]",
        "ldr x24, [x24, #2112]",
        "ret",
        ".arch_extension noaes",
        ".p2align 6",
        vg_aes_encrypt_blocks_aes = sym super::aes::vg_aes_encrypt_blocks_aes,
    )
}

/// The CPU features `vg_aes_cfb8_decrypt_aes` requires (`Artifact.features`).
pub(crate) const VG_AES_CFB8_DECRYPT_AES_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["aes"]);

/// AES-CFB8 decryption (NIST SP 800-38A §6.3, with 8-bit segments), in place: replaces the `len` bytes `C#₁ … C#ₙ` at `data` with `P#ⱼ = C#ⱼ ⊕ MSB₈(CIPH_K(Iⱼ))`, where `I₁` is the block at `*iv` and `Iⱼ₊₁` is `Iⱼ` without its first byte, followed by `C#ⱼ`, and `*iv` with `Iₙ₊₁` (leaving it unchanged if `len = 0`), so that a further call continues the message. `CIPH_K` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it.
///
/// Contract: `VG.Spec.Cfb8.aesDecryptContract`. Constant time: only the pointers, `rounds` and `len` may affect timing, not the key schedule, the input block or the data.
///
/// This implementation enciphers one block for each byte with `vg_aes_encrypt_blocks_aes`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `iv` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `len` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `iv`, `data` and `scratch` must not overlap each other or `schedule` (distinct Rust objects never do).
/// * None of `schedule`, `iv`, `data` and `scratch` may wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `aes` target feature.
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_aes_cfb8_decrypt_aes(schedule: *const [u8; 240], rounds: usize, iv: *mut [u8; 16], data: *mut u8, len: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        ".arch_extension aes",
        "str x19, [x5, #2064]",
        "str x20, [x5, #2072]",
        "str x21, [x5, #2080]",
        "str x22, [x5, #2088]",
        "str x23, [x5, #2096]",
        "str x30, [x5, #2104]",
        "str x24, [x5, #2112]",
        "add x19, x0, #0",
        "add x20, x1, #0",
        "add x21, x2, #0",
        "add x22, x3, #0",
        "add x23, x4, #0",
        "add x24, x5, #0",
        "cbz x23, 20f",
        "22:",
        "ldr x9, [x21, #0]",
        "str x9, [x24, #2048]",
        "ldr x9, [x21, #8]",
        "str x9, [x24, #2056]",
        "add x0, x19, #0",
        "add x1, x20, #0",
        "add x2, x24, #2048",
        "movz x3, #1, lsl #0",
        "add x4, x24, #0",
        "bl {vg_aes_encrypt_blocks_aes}",
        "ldrb w9, [x22, #0]",
        "ldrb w10, [x24, #2048]",
        "eor x10, x10, x9",
        "strb w10, [x22, #0]",
        "ldr x10, [x21, #0]",
        "ldr x11, [x21, #8]",
        "extr x12, x11, x10, #8",
        "extr x13, x9, x11, #8",
        "str x12, [x21, #0]",
        "str x13, [x21, #8]",
        "add x22, x22, #1",
        "sub x23, x23, #1",
        "cbnz x23, 22b",
        "b 21f",
        "20:",
        "21:",
        "ldr x19, [x24, #2064]",
        "ldr x20, [x24, #2072]",
        "ldr x21, [x24, #2080]",
        "ldr x22, [x24, #2088]",
        "ldr x23, [x24, #2096]",
        "ldr x30, [x24, #2104]",
        "ldr x24, [x24, #2112]",
        "ret",
        ".arch_extension noaes",
        ".p2align 6",
        vg_aes_encrypt_blocks_aes = sym super::aes::vg_aes_encrypt_blocks_aes,
    )
}

/// AES-CFB8 encryption (NIST SP 800-38A §6.3, with 8-bit segments), in place: replaces the `len` bytes `P#₁ … P#ₙ` at `data` with `C#ⱼ = P#ⱼ ⊕ MSB₈(CIPH_K(Iⱼ))`, where `I₁` is the block at `*iv` and `Iⱼ₊₁` is `Iⱼ` without its first byte, followed by `C#ⱼ`, and `*iv` with `Iₙ₊₁` (leaving it unchanged if `len = 0`), so that a further call continues the message. `CIPH_K` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it.
///
/// Contract: `VG.Spec.Cfb8.aesEncryptContract`. Constant time: only the pointers, `rounds` and `len` may affect timing, not the key schedule, the input block or the data.
///
/// This implementation enciphers one block for each byte with `vg_aes_encrypt_blocks`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `iv` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `len` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `iv`, `data` and `scratch` must not overlap each other or `schedule` (distinct Rust objects never do).
/// * None of `schedule`, `iv`, `data` and `scratch` may wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_aes_cfb8_encrypt(schedule: *const [u8; 240], rounds: usize, iv: *mut [u8; 16], data: *mut u8, len: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "str x19, [x5, #2064]",
        "str x20, [x5, #2072]",
        "str x21, [x5, #2080]",
        "str x22, [x5, #2088]",
        "str x23, [x5, #2096]",
        "str x30, [x5, #2104]",
        "str x24, [x5, #2112]",
        "add x19, x0, #0",
        "add x20, x1, #0",
        "add x21, x2, #0",
        "add x22, x3, #0",
        "add x23, x4, #0",
        "add x24, x5, #0",
        "cbz x23, 20f",
        "22:",
        "ldr x9, [x21, #0]",
        "str x9, [x24, #2048]",
        "ldr x9, [x21, #8]",
        "str x9, [x24, #2056]",
        "add x0, x19, #0",
        "add x1, x20, #0",
        "add x2, x24, #2048",
        "movz x3, #1, lsl #0",
        "add x4, x24, #0",
        "bl {vg_aes_encrypt_blocks}",
        "ldrb w9, [x22, #0]",
        "ldrb w10, [x24, #2048]",
        "eor x9, x9, x10",
        "strb w9, [x22, #0]",
        "ldr x10, [x21, #0]",
        "ldr x11, [x21, #8]",
        "extr x12, x11, x10, #8",
        "extr x13, x9, x11, #8",
        "str x12, [x21, #0]",
        "str x13, [x21, #8]",
        "add x22, x22, #1",
        "sub x23, x23, #1",
        "cbnz x23, 22b",
        "b 21f",
        "20:",
        "21:",
        "ldr x19, [x24, #2064]",
        "ldr x20, [x24, #2072]",
        "ldr x21, [x24, #2080]",
        "ldr x22, [x24, #2088]",
        "ldr x23, [x24, #2096]",
        "ldr x30, [x24, #2104]",
        "ldr x24, [x24, #2112]",
        "ret",
        ".p2align 6",
        vg_aes_encrypt_blocks = sym super::aes::vg_aes_encrypt_blocks,
    )
}

/// AES-CFB8 decryption (NIST SP 800-38A §6.3, with 8-bit segments), in place: replaces the `len` bytes `C#₁ … C#ₙ` at `data` with `P#ⱼ = C#ⱼ ⊕ MSB₈(CIPH_K(Iⱼ))`, where `I₁` is the block at `*iv` and `Iⱼ₊₁` is `Iⱼ` without its first byte, followed by `C#ⱼ`, and `*iv` with `Iₙ₊₁` (leaving it unchanged if `len = 0`), so that a further call continues the message. `CIPH_K` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it.
///
/// Contract: `VG.Spec.Cfb8.aesDecryptContract`. Constant time: only the pointers, `rounds` and `len` may affect timing, not the key schedule, the input block or the data.
///
/// This implementation enciphers one block for each byte with `vg_aes_encrypt_blocks`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `iv` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `len` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `iv`, `data` and `scratch` must not overlap each other or `schedule` (distinct Rust objects never do).
/// * None of `schedule`, `iv`, `data` and `scratch` may wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_aes_cfb8_decrypt(schedule: *const [u8; 240], rounds: usize, iv: *mut [u8; 16], data: *mut u8, len: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "str x19, [x5, #2064]",
        "str x20, [x5, #2072]",
        "str x21, [x5, #2080]",
        "str x22, [x5, #2088]",
        "str x23, [x5, #2096]",
        "str x30, [x5, #2104]",
        "str x24, [x5, #2112]",
        "add x19, x0, #0",
        "add x20, x1, #0",
        "add x21, x2, #0",
        "add x22, x3, #0",
        "add x23, x4, #0",
        "add x24, x5, #0",
        "cbz x23, 20f",
        "22:",
        "ldr x9, [x21, #0]",
        "str x9, [x24, #2048]",
        "ldr x9, [x21, #8]",
        "str x9, [x24, #2056]",
        "add x0, x19, #0",
        "add x1, x20, #0",
        "add x2, x24, #2048",
        "movz x3, #1, lsl #0",
        "add x4, x24, #0",
        "bl {vg_aes_encrypt_blocks}",
        "ldrb w9, [x22, #0]",
        "ldrb w10, [x24, #2048]",
        "eor x10, x10, x9",
        "strb w10, [x22, #0]",
        "ldr x10, [x21, #0]",
        "ldr x11, [x21, #8]",
        "extr x12, x11, x10, #8",
        "extr x13, x9, x11, #8",
        "str x12, [x21, #0]",
        "str x13, [x21, #8]",
        "add x22, x22, #1",
        "sub x23, x23, #1",
        "cbnz x23, 22b",
        "b 21f",
        "20:",
        "21:",
        "ldr x19, [x24, #2064]",
        "ldr x20, [x24, #2072]",
        "ldr x21, [x24, #2080]",
        "ldr x22, [x24, #2088]",
        "ldr x23, [x24, #2096]",
        "ldr x30, [x24, #2104]",
        "ldr x24, [x24, #2112]",
        "ret",
        ".p2align 6",
        vg_aes_encrypt_blocks = sym super::aes::vg_aes_encrypt_blocks,
    )
}
