name = "NIST CAVP FIPS 186-3 RSASSA-PSS signature generation and verification test vectors (the PSS files of the RSA test vectors)"
directories = ["nist-cavp-rsa-pss"]
url = "https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/dss/186-3rsatestvectors.zip"
sha256 = "8405aeb3572a4f98ed4b1a3ccb3f2f49e725462dd28ec4759d6a15d88855d19c"
retrieved = 2026-10-04
