name = "NIST CAVP AES Known Answer Test (KAT) vectors (the OFB GFSbox, KeySbox, VarKey and VarTxt .rsp files only)"
directories = ["nist-cavp-aes-kat-ofb"]
url = "https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/aes/KAT_AES.zip"
sha256 = "a203b16c9246b2ebae31dee5de21a606be80cf78ceabaca37150236fa098eb60"
retrieved = 2026-10-08
