name = "NIST CAVP ECDSA FIPS 186-4 signature verification test vectors (SigVer.rsp)"
directories = ["nist-cavp-ecdsa"]
url = "https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/dss/186-4ecdsatestvectors.zip"
sha256 = "fe47cc92b4cee418236125c9ffbcd9bb01c8c34e74a4ba195d954bcb72824752"
retrieved = "2026-10-03"
