name = "RFC 3713, A Description of the Camellia Encryption Algorithm (SBOX1 in Section 2.4.1, example data in Appendix A)"
directories = ["rfc3713"]
url = "https://www.rfc-editor.org/rfc/rfc3713.txt"
sha256 = "126cea1768aed9257fbdf52a4e1938eb15d79c8aacb83d14f60f1320d5b8770f"
retrieved = 2026-10-08
