// @generated by lean/Emit.lean. DO NOT EDIT.
//! Verified `aes_xts` functions for `x86_64`.
#![allow(dead_code)]

/// The CPU features `vg_aes_xts_encrypt_aesni` requires (`Artifact.features`).
pub(crate) const VG_AES_XTS_ENCRYPT_AESNI_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["aes"]);

/// XTS-AES encryption (IEEE Std 1619-2007 §5.3.1, NIST SP 800-38E) of whole blocks, in place: replaces the `n` 16-byte blocks `Pⱼ` at `data` with `Cⱼ = AES-enc(Key1, Pⱼ ⊕ Tⱼ) ⊕ Tⱼ`, where `T₀` is the tweak at `*tweak` and `Tⱼ₊₁ = Tⱼ ⊗ α` (§5.2), and `*tweak` with `Tₙ` (leaving it unchanged if `n = 0`), so that a further call continues the data unit. `AES-enc(Key1, ·)` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it. The caller computes the first tweak, `AES-enc(Key2, i)`, and steals ciphertext for a partial last block.
///
/// Contract: `VG.Spec.Xts.aesEncryptContract`. Constant time: only the pointers, `rounds` and `n` may affect timing, not the key schedule, the tweak or the data.
///
/// This implementation enciphers one block at a time with `vg_aes_encrypt_blocks_aesni`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `tweak` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `tweak`, `data` and `scratch` must not overlap each other or `schedule` (distinct Rust objects never do).
/// * None of `schedule`, `tweak`, `data` and `scratch` may overlap the return address on the stack or the 8 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `aes` target feature.
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_aes_xts_encrypt_aesni(schedule: *const [u8; 240], rounds: usize, tweak: *mut [u8; 16], data: *mut [u8; 16], n: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r9+2064], rbx",
        "mov QWORD PTR [r9+2072], rbp",
        "mov QWORD PTR [r9+2080], r12",
        "mov QWORD PTR [r9+2088], r13",
        "mov QWORD PTR [r9+2096], r14",
        "mov QWORD PTR [r9+2104], r15",
        "mov rbx, rdi",
        "mov rbp, rsi",
        "mov r12, rdx",
        "mov r13, rcx",
        "mov r14, r8",
        "mov r15, r9",
        "test r14, r14",
        "je 20f",
        "mov rax, QWORD PTR [r12]",
        "mov QWORD PTR [r15+2048], rax",
        "mov rax, QWORD PTR [r12+8]",
        "mov QWORD PTR [r15+2056], rax",
        "mov r10, r13",
        "mov r11, r14",
        "22:",
        "mov rax, QWORD PTR [r13]",
        "xor rax, QWORD PTR [r12]",
        "mov QWORD PTR [r13], rax",
        "mov rax, QWORD PTR [r13+8]",
        "xor rax, QWORD PTR [r12+8]",
        "mov QWORD PTR [r13+8], rax",
        "mov rax, QWORD PTR [r12]",
        "mov rcx, QWORD PTR [r12+8]",
        "add rax, rax",
        "adc rcx, rcx",
        "sbb rdx, rdx",
        "and rdx, 135",
        "xor rax, rdx",
        "mov QWORD PTR [r12], rax",
        "mov QWORD PTR [r12+8], rcx",
        "add r13, 16",
        "sub r14, 1",
        "jne 22b",
        "mov r13, r10",
        "mov r14, r11",
        "mov rax, QWORD PTR [r15+2048]",
        "mov QWORD PTR [r12], rax",
        "mov rax, QWORD PTR [r15+2056]",
        "mov QWORD PTR [r12+8], rax",
        "mov rdi, rbx",
        "mov rsi, rbp",
        "mov rdx, r13",
        "mov rcx, r14",
        "mov r8, r15",
        "call {vg_aes_encrypt_blocks_aesni}",
        "23:",
        "mov rax, QWORD PTR [r13]",
        "xor rax, QWORD PTR [r12]",
        "mov QWORD PTR [r13], rax",
        "mov rax, QWORD PTR [r13+8]",
        "xor rax, QWORD PTR [r12+8]",
        "mov QWORD PTR [r13+8], rax",
        "mov rax, QWORD PTR [r12]",
        "mov rcx, QWORD PTR [r12+8]",
        "add rax, rax",
        "adc rcx, rcx",
        "sbb rdx, rdx",
        "and rdx, 135",
        "xor rax, rdx",
        "mov QWORD PTR [r12], rax",
        "mov QWORD PTR [r12+8], rcx",
        "add r13, 16",
        "sub r14, 1",
        "jne 23b",
        "jmp 21f",
        "20:",
        "21:",
        "mov rbx, QWORD PTR [r15+2064]",
        "mov rbp, QWORD PTR [r15+2072]",
        "mov r12, QWORD PTR [r15+2080]",
        "mov r13, QWORD PTR [r15+2088]",
        "mov r14, QWORD PTR [r15+2096]",
        "mov r15, QWORD PTR [r15+2104]",
        "ret",
        ".p2align 6",
        vg_aes_encrypt_blocks_aesni = sym super::aes::vg_aes_encrypt_blocks_aesni,
    )
}

/// The CPU features `vg_aes_xts_decrypt_aesni` requires (`Artifact.features`).
pub(crate) const VG_AES_XTS_DECRYPT_AESNI_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["aes"]);

/// XTS-AES decryption (IEEE Std 1619-2007 §5.4.1, NIST SP 800-38E) of whole blocks, in place: replaces the `n` 16-byte blocks `Cⱼ` at `data` with `Pⱼ = AES-dec(Key1, Cⱼ ⊕ Tⱼ) ⊕ Tⱼ`, where `T₀` is the tweak at `*tweak` and `Tⱼ₊₁ = Tⱼ ⊗ α` (§5.2), and `*tweak` with `Tₙ` (leaving it unchanged if `n = 0`), so that a further call continues the data unit. `AES-dec(Key1, ·)` is the AES inverse cipher (FIPS 197 §5.3) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it. The caller computes the first tweak, `AES-enc(Key2, i)`, and steals ciphertext for a partial last block.
///
/// Contract: `VG.Spec.Xts.aesDecryptContract`. Constant time: only the pointers, `rounds` and `n` may affect timing, not the key schedule, the tweak or the data.
///
/// This implementation deciphers one block at a time with `vg_aes_decrypt_blocks_aesni`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `tweak` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `tweak`, `data` and `scratch` must not overlap each other or `schedule` (distinct Rust objects never do).
/// * None of `schedule`, `tweak`, `data` and `scratch` may overlap the return address on the stack or the 8 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `aes` target feature.
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_aes_xts_decrypt_aesni(schedule: *const [u8; 240], rounds: usize, tweak: *mut [u8; 16], data: *mut [u8; 16], n: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r9+2064], rbx",
        "mov QWORD PTR [r9+2072], rbp",
        "mov QWORD PTR [r9+2080], r12",
        "mov QWORD PTR [r9+2088], r13",
        "mov QWORD PTR [r9+2096], r14",
        "mov QWORD PTR [r9+2104], r15",
        "mov rbx, rdi",
        "mov rbp, rsi",
        "mov r12, rdx",
        "mov r13, rcx",
        "mov r14, r8",
        "mov r15, r9",
        "test r14, r14",
        "je 20f",
        "mov rax, QWORD PTR [r12]",
        "mov QWORD PTR [r15+2048], rax",
        "mov rax, QWORD PTR [r12+8]",
        "mov QWORD PTR [r15+2056], rax",
        "mov r10, r13",
        "mov r11, r14",
        "22:",
        "mov rax, QWORD PTR [r13]",
        "xor rax, QWORD PTR [r12]",
        "mov QWORD PTR [r13], rax",
        "mov rax, QWORD PTR [r13+8]",
        "xor rax, QWORD PTR [r12+8]",
        "mov QWORD PTR [r13+8], rax",
        "mov rax, QWORD PTR [r12]",
        "mov rcx, QWORD PTR [r12+8]",
        "add rax, rax",
        "adc rcx, rcx",
        "sbb rdx, rdx",
        "and rdx, 135",
        "xor rax, rdx",
        "mov QWORD PTR [r12], rax",
        "mov QWORD PTR [r12+8], rcx",
        "add r13, 16",
        "sub r14, 1",
        "jne 22b",
        "mov r13, r10",
        "mov r14, r11",
        "mov rax, QWORD PTR [r15+2048]",
        "mov QWORD PTR [r12], rax",
        "mov rax, QWORD PTR [r15+2056]",
        "mov QWORD PTR [r12+8], rax",
        "mov rdi, rbx",
        "mov rsi, rbp",
        "mov rdx, r13",
        "mov rcx, r14",
        "mov r8, r15",
        "call {vg_aes_decrypt_blocks_aesni}",
        "23:",
        "mov rax, QWORD PTR [r13]",
        "xor rax, QWORD PTR [r12]",
        "mov QWORD PTR [r13], rax",
        "mov rax, QWORD PTR [r13+8]",
        "xor rax, QWORD PTR [r12+8]",
        "mov QWORD PTR [r13+8], rax",
        "mov rax, QWORD PTR [r12]",
        "mov rcx, QWORD PTR [r12+8]",
        "add rax, rax",
        "adc rcx, rcx",
        "sbb rdx, rdx",
        "and rdx, 135",
        "xor rax, rdx",
        "mov QWORD PTR [r12], rax",
        "mov QWORD PTR [r12+8], rcx",
        "add r13, 16",
        "sub r14, 1",
        "jne 23b",
        "jmp 21f",
        "20:",
        "21:",
        "mov rbx, QWORD PTR [r15+2064]",
        "mov rbp, QWORD PTR [r15+2072]",
        "mov r12, QWORD PTR [r15+2080]",
        "mov r13, QWORD PTR [r15+2088]",
        "mov r14, QWORD PTR [r15+2096]",
        "mov r15, QWORD PTR [r15+2104]",
        "ret",
        ".p2align 6",
        vg_aes_decrypt_blocks_aesni = sym super::aes::vg_aes_decrypt_blocks_aesni,
    )
}

/// XTS-AES encryption (IEEE Std 1619-2007 §5.3.1, NIST SP 800-38E) of whole blocks, in place: replaces the `n` 16-byte blocks `Pⱼ` at `data` with `Cⱼ = AES-enc(Key1, Pⱼ ⊕ Tⱼ) ⊕ Tⱼ`, where `T₀` is the tweak at `*tweak` and `Tⱼ₊₁ = Tⱼ ⊗ α` (§5.2), and `*tweak` with `Tₙ` (leaving it unchanged if `n = 0`), so that a further call continues the data unit. `AES-enc(Key1, ·)` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it. The caller computes the first tweak, `AES-enc(Key2, i)`, and steals ciphertext for a partial last block.
///
/// Contract: `VG.Spec.Xts.aesEncryptContract`. Constant time: only the pointers, `rounds` and `n` may affect timing, not the key schedule, the tweak or the data.
///
/// This implementation enciphers one block at a time with `vg_aes_encrypt_blocks`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `tweak` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `tweak`, `data` and `scratch` must not overlap each other or `schedule` (distinct Rust objects never do).
/// * None of `schedule`, `tweak`, `data` and `scratch` may overlap the return address on the stack or the 8 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_aes_xts_encrypt(schedule: *const [u8; 240], rounds: usize, tweak: *mut [u8; 16], data: *mut [u8; 16], n: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r9+2064], rbx",
        "mov QWORD PTR [r9+2072], rbp",
        "mov QWORD PTR [r9+2080], r12",
        "mov QWORD PTR [r9+2088], r13",
        "mov QWORD PTR [r9+2096], r14",
        "mov QWORD PTR [r9+2104], r15",
        "mov rbx, rdi",
        "mov rbp, rsi",
        "mov r12, rdx",
        "mov r13, rcx",
        "mov r14, r8",
        "mov r15, r9",
        "test r14, r14",
        "je 20f",
        "mov rax, QWORD PTR [r12]",
        "mov QWORD PTR [r15+2048], rax",
        "mov rax, QWORD PTR [r12+8]",
        "mov QWORD PTR [r15+2056], rax",
        "mov r10, r13",
        "mov r11, r14",
        "22:",
        "mov rax, QWORD PTR [r13]",
        "xor rax, QWORD PTR [r12]",
        "mov QWORD PTR [r13], rax",
        "mov rax, QWORD PTR [r13+8]",
        "xor rax, QWORD PTR [r12+8]",
        "mov QWORD PTR [r13+8], rax",
        "mov rax, QWORD PTR [r12]",
        "mov rcx, QWORD PTR [r12+8]",
        "add rax, rax",
        "adc rcx, rcx",
        "sbb rdx, rdx",
        "and rdx, 135",
        "xor rax, rdx",
        "mov QWORD PTR [r12], rax",
        "mov QWORD PTR [r12+8], rcx",
        "add r13, 16",
        "sub r14, 1",
        "jne 22b",
        "mov r13, r10",
        "mov r14, r11",
        "mov rax, QWORD PTR [r15+2048]",
        "mov QWORD PTR [r12], rax",
        "mov rax, QWORD PTR [r15+2056]",
        "mov QWORD PTR [r12+8], rax",
        "mov rdi, rbx",
        "mov rsi, rbp",
        "mov rdx, r13",
        "mov rcx, r14",
        "mov r8, r15",
        "call {vg_aes_encrypt_blocks}",
        "23:",
        "mov rax, QWORD PTR [r13]",
        "xor rax, QWORD PTR [r12]",
        "mov QWORD PTR [r13], rax",
        "mov rax, QWORD PTR [r13+8]",
        "xor rax, QWORD PTR [r12+8]",
        "mov QWORD PTR [r13+8], rax",
        "mov rax, QWORD PTR [r12]",
        "mov rcx, QWORD PTR [r12+8]",
        "add rax, rax",
        "adc rcx, rcx",
        "sbb rdx, rdx",
        "and rdx, 135",
        "xor rax, rdx",
        "mov QWORD PTR [r12], rax",
        "mov QWORD PTR [r12+8], rcx",
        "add r13, 16",
        "sub r14, 1",
        "jne 23b",
        "jmp 21f",
        "20:",
        "21:",
        "mov rbx, QWORD PTR [r15+2064]",
        "mov rbp, QWORD PTR [r15+2072]",
        "mov r12, QWORD PTR [r15+2080]",
        "mov r13, QWORD PTR [r15+2088]",
        "mov r14, QWORD PTR [r15+2096]",
        "mov r15, QWORD PTR [r15+2104]",
        "ret",
        ".p2align 6",
        vg_aes_encrypt_blocks = sym super::aes::vg_aes_encrypt_blocks,
    )
}

/// XTS-AES decryption (IEEE Std 1619-2007 §5.4.1, NIST SP 800-38E) of whole blocks, in place: replaces the `n` 16-byte blocks `Cⱼ` at `data` with `Pⱼ = AES-dec(Key1, Cⱼ ⊕ Tⱼ) ⊕ Tⱼ`, where `T₀` is the tweak at `*tweak` and `Tⱼ₊₁ = Tⱼ ⊗ α` (§5.2), and `*tweak` with `Tₙ` (leaving it unchanged if `n = 0`), so that a further call continues the data unit. `AES-dec(Key1, ·)` is the AES inverse cipher (FIPS 197 §5.3) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it. The caller computes the first tweak, `AES-enc(Key2, i)`, and steals ciphertext for a partial last block.
///
/// Contract: `VG.Spec.Xts.aesDecryptContract`. Constant time: only the pointers, `rounds` and `n` may affect timing, not the key schedule, the tweak or the data.
///
/// This implementation deciphers one block at a time with `vg_aes_decrypt_blocks`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `tweak` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `tweak`, `data` and `scratch` must not overlap each other or `schedule` (distinct Rust objects never do).
/// * None of `schedule`, `tweak`, `data` and `scratch` may overlap the return address on the stack or the 8 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_aes_xts_decrypt(schedule: *const [u8; 240], rounds: usize, tweak: *mut [u8; 16], data: *mut [u8; 16], n: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r9+2064], rbx",
        "mov QWORD PTR [r9+2072], rbp",
        "mov QWORD PTR [r9+2080], r12",
        "mov QWORD PTR [r9+2088], r13",
        "mov QWORD PTR [r9+2096], r14",
        "mov QWORD PTR [r9+2104], r15",
        "mov rbx, rdi",
        "mov rbp, rsi",
        "mov r12, rdx",
        "mov r13, rcx",
        "mov r14, r8",
        "mov r15, r9",
        "test r14, r14",
        "je 20f",
        "mov rax, QWORD PTR [r12]",
        "mov QWORD PTR [r15+2048], rax",
        "mov rax, QWORD PTR [r12+8]",
        "mov QWORD PTR [r15+2056], rax",
        "mov r10, r13",
        "mov r11, r14",
        "22:",
        "mov rax, QWORD PTR [r13]",
        "xor rax, QWORD PTR [r12]",
        "mov QWORD PTR [r13], rax",
        "mov rax, QWORD PTR [r13+8]",
        "xor rax, QWORD PTR [r12+8]",
        "mov QWORD PTR [r13+8], rax",
        "mov rax, QWORD PTR [r12]",
        "mov rcx, QWORD PTR [r12+8]",
        "add rax, rax",
        "adc rcx, rcx",
        "sbb rdx, rdx",
        "and rdx, 135",
        "xor rax, rdx",
        "mov QWORD PTR [r12], rax",
        "mov QWORD PTR [r12+8], rcx",
        "add r13, 16",
        "sub r14, 1",
        "jne 22b",
        "mov r13, r10",
        "mov r14, r11",
        "mov rax, QWORD PTR [r15+2048]",
        "mov QWORD PTR [r12], rax",
        "mov rax, QWORD PTR [r15+2056]",
        "mov QWORD PTR [r12+8], rax",
        "mov rdi, rbx",
        "mov rsi, rbp",
        "mov rdx, r13",
        "mov rcx, r14",
        "mov r8, r15",
        "call {vg_aes_decrypt_blocks}",
        "23:",
        "mov rax, QWORD PTR [r13]",
        "xor rax, QWORD PTR [r12]",
        "mov QWORD PTR [r13], rax",
        "mov rax, QWORD PTR [r13+8]",
        "xor rax, QWORD PTR [r12+8]",
        "mov QWORD PTR [r13+8], rax",
        "mov rax, QWORD PTR [r12]",
        "mov rcx, QWORD PTR [r12+8]",
        "add rax, rax",
        "adc rcx, rcx",
        "sbb rdx, rdx",
        "and rdx, 135",
        "xor rax, rdx",
        "mov QWORD PTR [r12], rax",
        "mov QWORD PTR [r12+8], rcx",
        "add r13, 16",
        "sub r14, 1",
        "jne 23b",
        "jmp 21f",
        "20:",
        "21:",
        "mov rbx, QWORD PTR [r15+2064]",
        "mov rbp, QWORD PTR [r15+2072]",
        "mov r12, QWORD PTR [r15+2080]",
        "mov r13, QWORD PTR [r15+2088]",
        "mov r14, QWORD PTR [r15+2096]",
        "mov r15, QWORD PTR [r15+2104]",
        "ret",
        ".p2align 6",
        vg_aes_decrypt_blocks = sym super::aes::vg_aes_decrypt_blocks,
    )
}

/// The CPU features `vg_aes_xts_encrypt_vaes` requires (`Artifact.features`).
pub(crate) const VG_AES_XTS_ENCRYPT_VAES_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["aes", "avx", "avx2", "vaes"]);

/// XTS-AES encryption (IEEE Std 1619-2007 §5.3.1, NIST SP 800-38E) of whole blocks, in place: replaces the `n` 16-byte blocks `Pⱼ` at `data` with `Cⱼ = AES-enc(Key1, Pⱼ ⊕ Tⱼ) ⊕ Tⱼ`, where `T₀` is the tweak at `*tweak` and `Tⱼ₊₁ = Tⱼ ⊗ α` (§5.2), and `*tweak` with `Tₙ` (leaving it unchanged if `n = 0`), so that a further call continues the data unit. `AES-enc(Key1, ·)` is AES (FIPS 197) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it. The caller computes the first tweak, `AES-enc(Key2, i)`, and steals ciphertext for a partial last block.
///
/// Contract: `VG.Spec.Xts.aesEncryptContract`. Constant time: only the pointers, `rounds` and `n` may affect timing, not the key schedule, the tweak or the data.
///
/// This implementation enciphers one block at a time with `vg_aes_encrypt_blocks_vaes`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `tweak` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `tweak`, `data` and `scratch` must not overlap each other or `schedule` (distinct Rust objects never do).
/// * None of `schedule`, `tweak`, `data` and `scratch` may overlap the return address on the stack or the 8 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `aes`, `avx`, `avx2` and `vaes` target features.
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_aes_xts_encrypt_vaes(schedule: *const [u8; 240], rounds: usize, tweak: *mut [u8; 16], data: *mut [u8; 16], n: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r9+2064], rbx",
        "mov QWORD PTR [r9+2072], rbp",
        "mov QWORD PTR [r9+2080], r12",
        "mov QWORD PTR [r9+2088], r13",
        "mov QWORD PTR [r9+2096], r14",
        "mov QWORD PTR [r9+2104], r15",
        "mov rbx, rdi",
        "mov rbp, rsi",
        "mov r12, rdx",
        "mov r13, rcx",
        "mov r14, r8",
        "mov r15, r9",
        "test r14, r14",
        "je 20f",
        "22:",
        "mov rax, QWORD PTR [r13]",
        "xor rax, QWORD PTR [r12]",
        "mov QWORD PTR [r13], rax",
        "mov rax, QWORD PTR [r13+8]",
        "xor rax, QWORD PTR [r12+8]",
        "mov QWORD PTR [r13+8], rax",
        "mov rdi, rbx",
        "mov rsi, rbp",
        "mov rdx, r13",
        "mov ecx, 1",
        "mov r8, r15",
        "call {vg_aes_encrypt_blocks_vaes}",
        "mov rax, QWORD PTR [r13]",
        "xor rax, QWORD PTR [r12]",
        "mov QWORD PTR [r13], rax",
        "mov rax, QWORD PTR [r13+8]",
        "xor rax, QWORD PTR [r12+8]",
        "mov QWORD PTR [r13+8], rax",
        "mov rax, QWORD PTR [r12]",
        "mov rcx, QWORD PTR [r12+8]",
        "add rax, rax",
        "adc rcx, rcx",
        "sbb rdx, rdx",
        "and rdx, 135",
        "xor rax, rdx",
        "mov QWORD PTR [r12], rax",
        "mov QWORD PTR [r12+8], rcx",
        "add r13, 16",
        "sub r14, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov rbx, QWORD PTR [r15+2064]",
        "mov rbp, QWORD PTR [r15+2072]",
        "mov r12, QWORD PTR [r15+2080]",
        "mov r13, QWORD PTR [r15+2088]",
        "mov r14, QWORD PTR [r15+2096]",
        "mov r15, QWORD PTR [r15+2104]",
        "ret",
        ".p2align 6",
        vg_aes_encrypt_blocks_vaes = sym super::aes::vg_aes_encrypt_blocks_vaes,
    )
}

/// The CPU features `vg_aes_xts_decrypt_vaes` requires (`Artifact.features`).
pub(crate) const VG_AES_XTS_DECRYPT_VAES_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["aes", "avx", "avx2", "vaes"]);

/// XTS-AES decryption (IEEE Std 1619-2007 §5.4.1, NIST SP 800-38E) of whole blocks, in place: replaces the `n` 16-byte blocks `Cⱼ` at `data` with `Pⱼ = AES-dec(Key1, Cⱼ ⊕ Tⱼ) ⊕ Tⱼ`, where `T₀` is the tweak at `*tweak` and `Tⱼ₊₁ = Tⱼ ⊗ α` (§5.2), and `*tweak` with `Tₙ` (leaving it unchanged if `n = 0`), so that a further call continues the data unit. `AES-dec(Key1, ·)` is the AES inverse cipher (FIPS 197 §5.3) with `rounds` rounds and the key schedule in the first `16 * (rounds + 1)` bytes of `*schedule`, as `vg_aes_expand_key` writes it. The caller computes the first tweak, `AES-enc(Key2, i)`, and steals ciphertext for a partial last block.
///
/// Contract: `VG.Spec.Xts.aesDecryptContract`. Constant time: only the pointers, `rounds` and `n` may affect timing, not the key schedule, the tweak or the data.
///
/// This implementation deciphers one block at a time with `vg_aes_decrypt_blocks_vaes`.
///
/// # Safety
///
/// * `schedule` must be valid for reads of 240 bytes.
/// * `tweak` must be valid for reads and writes of 16 bytes.
/// * `data` must be valid for reads and writes of `16 * n` bytes.
/// * `scratch` must be valid for reads and writes of 2176 bytes.
/// * `rounds` must be 10, 12 or 14.
/// * The contents of `scratch` on return are unspecified.
/// * `tweak`, `data` and `scratch` must not overlap each other or `schedule` (distinct Rust objects never do).
/// * None of `schedule`, `tweak`, `data` and `scratch` may overlap the return address on the stack or the 8 bytes of stack below it, or wrap around the end of the address space (no Rust object does).
/// * The CPU must support the `aes`, `avx`, `avx2` and `vaes` target features.
#[unsafe(naked)]
pub(crate) unsafe extern "sysv64" fn vg_aes_xts_decrypt_vaes(schedule: *const [u8; 240], rounds: usize, tweak: *mut [u8; 16], data: *mut [u8; 16], n: usize, scratch: *mut [u64; 272]) {
    core::arch::naked_asm!(
        "mov QWORD PTR [r9+2064], rbx",
        "mov QWORD PTR [r9+2072], rbp",
        "mov QWORD PTR [r9+2080], r12",
        "mov QWORD PTR [r9+2088], r13",
        "mov QWORD PTR [r9+2096], r14",
        "mov QWORD PTR [r9+2104], r15",
        "mov rbx, rdi",
        "mov rbp, rsi",
        "mov r12, rdx",
        "mov r13, rcx",
        "mov r14, r8",
        "mov r15, r9",
        "test r14, r14",
        "je 20f",
        "22:",
        "mov rax, QWORD PTR [r13]",
        "xor rax, QWORD PTR [r12]",
        "mov QWORD PTR [r13], rax",
        "mov rax, QWORD PTR [r13+8]",
        "xor rax, QWORD PTR [r12+8]",
        "mov QWORD PTR [r13+8], rax",
        "mov rdi, rbx",
        "mov rsi, rbp",
        "mov rdx, r13",
        "mov ecx, 1",
        "mov r8, r15",
        "call {vg_aes_decrypt_blocks_vaes}",
        "mov rax, QWORD PTR [r13]",
        "xor rax, QWORD PTR [r12]",
        "mov QWORD PTR [r13], rax",
        "mov rax, QWORD PTR [r13+8]",
        "xor rax, QWORD PTR [r12+8]",
        "mov QWORD PTR [r13+8], rax",
        "mov rax, QWORD PTR [r12]",
        "mov rcx, QWORD PTR [r12+8]",
        "add rax, rax",
        "adc rcx, rcx",
        "sbb rdx, rdx",
        "and rdx, 135",
        "xor rax, rdx",
        "mov QWORD PTR [r12], rax",
        "mov QWORD PTR [r12+8], rcx",
        "add r13, 16",
        "sub r14, 1",
        "jne 22b",
        "jmp 21f",
        "20:",
        "21:",
        "mov rbx, QWORD PTR [r15+2064]",
        "mov rbp, QWORD PTR [r15+2072]",
        "mov r12, QWORD PTR [r15+2080]",
        "mov r13, QWORD PTR [r15+2088]",
        "mov r14, QWORD PTR [r15+2096]",
        "mov r15, QWORD PTR [r15+2104]",
        "ret",
        ".p2align 6",
        vg_aes_decrypt_blocks_vaes = sym super::aes::vg_aes_decrypt_blocks_vaes,
    )
}
