"""Uses of slow patterns that remain, per file (see `check_lean_speed.py`).

`DECIDE_SIMP_ALLOWED`: `simp (config := {decide := true})` whose replacement
by simprocs broke the proof (`decide` evaluated a closed fact that no simproc
reduces, such as a definition applied to literals, or the goal's shape
changed), or was not cheaper: in the shared block-runner and layout macros
`decide` only decides small closed facts, and simprocs measured slower (e.g.
ML-DSA x86-64 `lay`: 87e9 to 154e9 instructions in one user). Lower a count
when you remove a use; raise one or add a file only with a measurement
showing `decide` is the cheaper option there.

`BARE_ASSUMPTION_ALLOWED`: bare `assumption` after `<;>` or in `first | …`
that needs default transparency (the hypothesis matches only up to unfolding)
or was not yet converted. Same rule.
"""

DECIDE_SIMP_ALLOWED = {
    "VerifiedGarbage/Proof/Aes/AArch64/Aese/Ctr32.lean": 1,
    "VerifiedGarbage/Proof/Aes/AArch64/Ctr32.lean": 4,
    "VerifiedGarbage/Proof/Aes/AArch64/ExpandKey.lean": 18,
    "VerifiedGarbage/Proof/Aes/X86/AesNi/Ctr32.lean": 9,
    "VerifiedGarbage/Proof/Aes/X86/AesNi/KeyBlocks.lean": 1,
    "VerifiedGarbage/Proof/Aes/X86_64/AesNi/Ctr32.lean": 8,
    "VerifiedGarbage/Proof/Aes/X86_64/AesNi/ExpandKey.lean": 2,
    "VerifiedGarbage/Proof/Aes/X86_64/Ctr32.lean": 4,
    "VerifiedGarbage/Proof/Aes/X86_64/ExpandKey.lean": 3,
    "VerifiedGarbage/Proof/AesSiv/AArch64/Verified.lean": 4,
    "VerifiedGarbage/Proof/AesSiv/X86_64/Frame.lean": 44,
    "VerifiedGarbage/Proof/Blake2/AArch64/Compress.lean": 11,
    "VerifiedGarbage/Proof/Blake2/Arm/Blake2b.lean": 9,
    "VerifiedGarbage/Proof/Blake2/Arm/CompressS/Compress.lean": 11,
    "VerifiedGarbage/Proof/Blake2/X86/CompressB/Verified.lean": 3,
    "VerifiedGarbage/Proof/Blake2/X86_64/Compress.lean": 16,
    "VerifiedGarbage/Proof/Blake2/X86_64/Stream/Verified.lean": 4,
    "VerifiedGarbage/Proof/ChaCha20/AArch64/Mixed5/Xor.lean": 1,
    "VerifiedGarbage/Proof/ChaCha20/AArch64/Mixed8/Xor.lean": 2,
    "VerifiedGarbage/Proof/ChaCha20/AArch64/Neon4/Xor.lean": 3,
    "VerifiedGarbage/Proof/ChaCha20/AArch64/Rows6/Xor.lean": 9,
    "VerifiedGarbage/Proof/ChaCha20/AArch64/Stream/ApplyCT.lean": 5,
    "VerifiedGarbage/Proof/ChaCha20/AArch64/Stream/Init.lean": 4,
    "VerifiedGarbage/Proof/ChaCha20/Arm/Stream/ApplyCT.lean": 8,
    "VerifiedGarbage/Proof/ChaCha20/Arm/Stream/Init.lean": 2,
    "VerifiedGarbage/Proof/ChaCha20/Arm/Xor.lean": 3,
    "VerifiedGarbage/Proof/ChaCha20/X86/Stream/ApplyCT.lean": 45,
    "VerifiedGarbage/Proof/ChaCha20/X86/Stream/Init.lean": 6,
    "VerifiedGarbage/Proof/ChaCha20/X86/Xor.lean": 10,
    "VerifiedGarbage/Proof/ChaCha20/X86_64/Avx2/Xor.lean": 2,
    "VerifiedGarbage/Proof/ChaCha20/X86_64/Avx512/Xor.lean": 1,
    "VerifiedGarbage/Proof/ChaCha20/X86_64/Stream/ApplyCT.lean": 45,
    "VerifiedGarbage/Proof/ChaCha20/X86_64/Stream/Init.lean": 4,
    "VerifiedGarbage/Proof/ChaCha20/X86_64/Xor.lean": 17,
    "VerifiedGarbage/Proof/ChaCha20Poly1305/AArch64/Poly.lean": 7,
    "VerifiedGarbage/Proof/ChaCha20Poly1305/AArch64/Stitched/Rest.lean": 1,
    "VerifiedGarbage/Proof/ChaCha20Poly1305/X86/Verified.lean": 10,
    "VerifiedGarbage/Proof/ChaCha20Poly1305/X86_64/Verified.lean": 19,
    "VerifiedGarbage/Proof/CmacAes/AArch64/Verified.lean": 6,
    "VerifiedGarbage/Proof/CmacAes/Stream/AArch64/Frame.lean": 14,
    "VerifiedGarbage/Proof/CmacAes/Stream/X86_64/Verified.lean": 5,
    "VerifiedGarbage/Proof/CmacAes/X86_64/Verified.lean": 1,
    "VerifiedGarbage/Proof/CmacTripleDes/AArch64/Frame.lean": 3,
    "VerifiedGarbage/Proof/CmacTripleDes/Arm/Frame.lean": 6,
    "VerifiedGarbage/Proof/CmacTripleDes/X86_64/Frame.lean": 3,
    "VerifiedGarbage/Proof/Ct/AArch64.lean": 1,
    "VerifiedGarbage/Proof/Curve448/AArch64/Fast/Field.lean": 2,
    "VerifiedGarbage/Proof/Curve448/AArch64/Neon/Mul2.lean": 3,
    "VerifiedGarbage/Proof/Ed448/X86_64/BaseVerified.lean": 2,
    "VerifiedGarbage/Proof/Gcm/AArch64/Ghash.lean": 10,
    "VerifiedGarbage/Proof/Gcm/Arm/Ghash.lean": 3,
    "VerifiedGarbage/Proof/Gcm/X86_64/Ghash.lean": 10,
    "VerifiedGarbage/Proof/Gcm/X86_64/Pclmul/Ghash.lean": 6,
    "VerifiedGarbage/Proof/Md5/AArch64/Compress.lean": 4,
    "VerifiedGarbage/Proof/Md5/Arm/Compress.lean": 5,
    "VerifiedGarbage/Proof/Md5/StateMem.lean": 1,
    "VerifiedGarbage/Proof/Md5/X86/Compress.lean": 3,
    "VerifiedGarbage/Proof/Md5/X86_64/Compress.lean": 4,
    "VerifiedGarbage/Proof/Md5/X86_64/Stream/Init.lean": 1,
    "VerifiedGarbage/Proof/MdStream/X86_64/Words.lean": 6,
    "VerifiedGarbage/Proof/MlDsa/AArch64/Arith/AddSub.lean": 1,
    "VerifiedGarbage/Proof/MlDsa/AArch64/KeyGen/Inst.lean": 1,
    "VerifiedGarbage/Proof/MlDsa/AArch64/Message/Verified.lean": 2,
    "VerifiedGarbage/Proof/MlDsa/AArch64/Verify/Inst.lean": 1,
    "VerifiedGarbage/Proof/MlDsa/Arm/Arith/AddSub.lean": 1,
    "VerifiedGarbage/Proof/MlDsa/Arm/KeyGen/Inst.lean": 1,
    "VerifiedGarbage/Proof/MlDsa/Arm/Message/Verified.lean": 2,
    "VerifiedGarbage/Proof/MlDsa/Arm/Sample/ExpandMask.lean": 1,
    "VerifiedGarbage/Proof/MlDsa/Arm/Verify/Inst.lean": 4,
    "VerifiedGarbage/Proof/MlDsa/X86/KeyGen/Inst.lean": 1,
    "VerifiedGarbage/Proof/MlDsa/X86/Message/Verified.lean": 3,
    "VerifiedGarbage/Proof/MlDsa/X86/Pack/HintPack.lean": 1,
    "VerifiedGarbage/Proof/MlDsa/X86/Pack/Run.lean": 1,
    "VerifiedGarbage/Proof/MlDsa/X86/Sample/ExpandMask.lean": 4,
    "VerifiedGarbage/Proof/MlDsa/X86_64/KeyGen/Inst.lean": 1,
    "VerifiedGarbage/Proof/MlKem/Arm/Add.lean": 2,
    "VerifiedGarbage/Proof/MlKem/X86/AddSub.lean": 1,
    "VerifiedGarbage/Proof/MlKem/X86/DecodeDecompress.lean": 1,
    "VerifiedGarbage/Proof/MlKem/X86/Mul.lean": 3,
    "VerifiedGarbage/Proof/MlKem/X86_64/AddSub.lean": 2,
    "VerifiedGarbage/Proof/MlKem/X86_64/Wp.lean": 1,
    "VerifiedGarbage/Proof/Pbkdf2/X86_64/IterateCT.lean": 3,
    "VerifiedGarbage/Proof/Poly1305/AArch64/Init.lean": 23,
    "VerifiedGarbage/Proof/Poly1305/AArch64/Radix64/Blocks.lean": 11,
    "VerifiedGarbage/Proof/Poly1305/X86/Finalize.lean": 3,
    "VerifiedGarbage/Proof/Poly1305/X86_64/Avx2/Blocks.lean": 12,
    "VerifiedGarbage/Proof/Poly1305/X86_64/Avx512/Blocks.lean": 3,
    "VerifiedGarbage/Proof/Poly1305/X86_64/Blocks.lean": 14,
    "VerifiedGarbage/Proof/Poly1305/X86_64/Finalize.lean": 2,
    "VerifiedGarbage/Proof/Poly1305/X86_64/Frame.lean": 2,
    "VerifiedGarbage/Proof/Poly1305/X86_64/Init.lean": 3,
    "VerifiedGarbage/Proof/Rc2/AArch64/Block.lean": 5,
    "VerifiedGarbage/Proof/Rc2/AArch64/Key.lean": 9,
    "VerifiedGarbage/Proof/Rc2/Arm/Block.lean": 6,
    "VerifiedGarbage/Proof/Rc2/Arm/Cbc/Verified.lean": 1,
    "VerifiedGarbage/Proof/Rc2/Arm/Key.lean": 8,
    "VerifiedGarbage/Proof/Rc2/X86/Block.lean": 1,
    "VerifiedGarbage/Proof/Rc2/X86/Key.lean": 2,
    "VerifiedGarbage/Proof/Rc2/X86_64/Block.lean": 6,
    "VerifiedGarbage/Proof/Rc2/X86_64/Key.lean": 11,
    "VerifiedGarbage/Proof/Rc2/X86_64/Stream/Frame.lean": 2,
    "VerifiedGarbage/Proof/Rc4/AArch64/VerifiedApply.lean": 1,
    "VerifiedGarbage/Proof/Sha1/AArch64/Compress.lean": 5,
    "VerifiedGarbage/Proof/Sha1/AArch64/Sha2/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha1/Arm/Compress.lean": 4,
    "VerifiedGarbage/Proof/Sha1/StateMem.lean": 1,
    "VerifiedGarbage/Proof/Sha1/X86/Compress.lean": 6,
    "VerifiedGarbage/Proof/Sha1/X86_64/Compress.lean": 4,
    "VerifiedGarbage/Proof/Sha1/X86_64/ShaNi/Compress.lean": 4,
    "VerifiedGarbage/Proof/Sha1/X86_64/Stream/Init.lean": 1,
    "VerifiedGarbage/Proof/Sha256/AArch64/Compress.lean": 4,
    "VerifiedGarbage/Proof/Sha256/Arm/Compress.lean": 4,
    "VerifiedGarbage/Proof/Sha256/StateMem.lean": 1,
    "VerifiedGarbage/Proof/Sha256/X86/Compress.lean": 3,
    "VerifiedGarbage/Proof/Sha256/X86/ShaNi/Verified.lean": 3,
    "VerifiedGarbage/Proof/Sha256/X86_64/Avx2/Compress.lean": 8,
    "VerifiedGarbage/Proof/Sha256/X86_64/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha256/X86_64/ShaNi/Compress.lean": 3,
    "VerifiedGarbage/Proof/Sha256/X86_64/Shared.lean": 1,
    "VerifiedGarbage/Proof/Sha512/AArch64/Compress.lean": 6,
    "VerifiedGarbage/Proof/Sha512/AArch64/Sha3/Compress.lean": 3,
    "VerifiedGarbage/Proof/Sha512/X86_64/Avx2/Compress.lean": 8,
    "VerifiedGarbage/Proof/Sha512/X86_64/ShaNi/Compress.lean": 5,
    "VerifiedGarbage/Proof/Sha512/X86_64/Stream/Init.lean": 1,
    "VerifiedGarbage/Proof/Sha512/X86_64/Wide.lean": 4,
    "VerifiedGarbage/Proof/TripleDes/Arm/Key/Verified.lean": 3,
    "VerifiedGarbage/Proof/X25519/X86/Verified.lean": 3,
    "VerifiedGarbage/Proof/X25519/X86_64/Ifma/Verified.lean": 1,
    "VerifiedGarbage/Proof/X25519/X86_64/Verified.lean": 3,
    "VerifiedGarbage/Proof/X448/AArch64/Fast/Verified.lean": 2,
    "VerifiedGarbage/Proof/X448/AArch64/Main.lean": 7,
    "VerifiedGarbage/Proof/X448/AArch64/PointwiseSmall.lean": 4,
    "VerifiedGarbage/Proof/X448/AArch64/Weak/Main.lean": 2,
    "VerifiedGarbage/Proof/X448/Arm/Verified.lean": 11,
    "VerifiedGarbage/Proof/X448/Encoding.lean": 1,
    "VerifiedGarbage/Proof/X448/Wide/TailMul.lean": 3,
    "VerifiedGarbage/Proof/X448/X86/Verified.lean": 11,
    "VerifiedGarbage/Proof/X448/X86_64/Verified.lean": 5,
    "VerifiedGarbage/Proof/Zeroize/Arm.lean": 1,
}

BARE_ASSUMPTION_ALLOWED = {
    "VerifiedGarbage/Proof/Aes/X86_64/Vaes/Ctr32.lean": 2,
    "VerifiedGarbage/Proof/AesGcm/X86_64/Blocks/CT.lean": 1,
    "VerifiedGarbage/Proof/AesSiv/X86_64/Frame.lean": 1,
    "VerifiedGarbage/Proof/Argon2/AArch64/Compress.lean": 1,
    "VerifiedGarbage/Proof/Argon2/X86/Divide.lean": 1,
    "VerifiedGarbage/Proof/Argon2/X86_64/Compress.lean": 1,
    "VerifiedGarbage/Proof/Blake2/AArch64/Compress.lean": 1,
    "VerifiedGarbage/Proof/Blake2/AArch64/Stream/Verified.lean": 3,
    "VerifiedGarbage/Proof/Blake2/Arm/Blake2b.lean": 1,
    "VerifiedGarbage/Proof/Blake2/Arm/CompressS/Compress.lean": 1,
    "VerifiedGarbage/Proof/Blake2/Arm/Stream/Verified.lean": 1,
    "VerifiedGarbage/Proof/Blake2/X86_64/Compress.lean": 1,
    "VerifiedGarbage/Proof/Blake2/X86_64/Stream/Verified.lean": 3,
    "VerifiedGarbage/Proof/CmacTripleDes/AArch64/Frame.lean": 3,
    "VerifiedGarbage/Proof/CmacTripleDes/Arm/Frame.lean": 2,
    "VerifiedGarbage/Proof/CmacTripleDes/X86_64/Frame.lean": 3,
    "VerifiedGarbage/Proof/Ed25519/AArch64/MulAddVerified.lean": 1,
    "VerifiedGarbage/Proof/Ed25519/AArch64/ScalarVerified.lean": 1,
    "VerifiedGarbage/Proof/Ed25519/Arm/ScalarMulAddVerified.lean": 1,
    "VerifiedGarbage/Proof/Ed25519/Arm/ScalarVerified.lean": 1,
    "VerifiedGarbage/Proof/Ed25519/X86_64/MulAddVerified.lean": 1,
    "VerifiedGarbage/Proof/Ed25519/X86_64/ScalarVerified.lean": 1,
    "VerifiedGarbage/Proof/Ed448/X86_64/BaseVerified.lean": 1,
    "VerifiedGarbage/Proof/Ed448/X86_64/ScalarVerified.lean": 2,
    "VerifiedGarbage/Proof/Ed448/X86_64/VerifyVerified.lean": 1,
    "VerifiedGarbage/Proof/Gcm/X86_64/Vpclmul/Ghash.lean": 1,
    "VerifiedGarbage/Proof/Md5/AArch64/Compress.lean": 1,
    "VerifiedGarbage/Proof/Md5/Arm/Compress.lean": 1,
    "VerifiedGarbage/Proof/Md5/X86_64/Compress.lean": 1,
    "VerifiedGarbage/Proof/MdStream/AArch64/Words.lean": 2,
    "VerifiedGarbage/Proof/MdStream/Arm/Words.lean": 2,
    "VerifiedGarbage/Proof/MdStream/X86_64/Words.lean": 1,
    "VerifiedGarbage/Proof/MlDsa/Arm/KeyGen/Inst.lean": 1,
    "VerifiedGarbage/Proof/MlKem/AArch64/Encaps.lean": 4,
    "VerifiedGarbage/Proof/MlKem/AArch64/KeyGen.lean": 1,
    "VerifiedGarbage/Proof/Poly1305/X86/Finalize.lean": 1,
    "VerifiedGarbage/Proof/Rc2/Arm/Stream/Frame.lean": 2,
    "VerifiedGarbage/Proof/Sha1/AArch64/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha1/AArch64/Sha2/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha1/Arm/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha1/X86_64/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha1/X86_64/ShaNi/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha256/AArch64/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha256/AArch64/Sha2/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha256/Arm/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha256/X86_64/Avx2/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha256/X86_64/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha256/X86_64/ShaNi/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha512/AArch64/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha512/AArch64/Sha3/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha512/Arm/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha512/X86_64/Avx2/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha512/X86_64/ShaNi/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha512/X86_64/Wide.lean": 1,
}

# Proofs that unfold a stack-depth function and close it by `omega` without
# `Nat.max_le` (see `check_lean_speed.py`): an induction over any code (one
# `max` of two variables per case), and proofs being changed elsewhere when
# the rule was added. Same rule.
DEPTH_OMEGA_ALLOWED = {
    "VerifiedGarbage/Proof/MlKem/Arm/CallF.lean": 1,
    "VerifiedGarbage/Proof/Pbkdf2/Md/AArch64/Core.lean": 3,
}

# Uses of `Exec.preservedV`, `WP.preservedV` or `WP.withPreservedV` that leave
# the check of every instruction to its default `decide +kernel` (see
# `check_lean_speed.py`), in proofs that were being changed elsewhere when the
# rule was added: pass `(by lit_decide)`. Same rule.
DEFAULT_CERT_ALLOWED = {
    "VerifiedGarbage/Proof/Md5/AArch64/Compress.lean": 1,
    "VerifiedGarbage/Proof/Md5/AArch64/Stream/Init.lean": 1,
    "VerifiedGarbage/Proof/Sha1/AArch64/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha1/AArch64/Sha2/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha1/AArch64/Stream/Init.lean": 1,
    "VerifiedGarbage/Proof/Sha256/AArch64/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha256/AArch64/Sha2/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha3/AArch64/Permute.lean": 1,
    "VerifiedGarbage/Proof/Sha512/AArch64/Compress.lean": 1,
    "VerifiedGarbage/Proof/Sha512/AArch64/Sha3/Compress.lean": 1,
}
