// @generated by lean/Emit.lean. DO NOT EDIT.
//! Verified `ct` functions for `powerpc64le`.
#![allow(dead_code)]

/// Compares two byte strings in constant time: returns 1 if the `a_len` bytes at `a` are the `b_len` bytes at `b` (so byte strings of different lengths are unequal), and 0 otherwise. Writes no memory.
///
/// Contract: `VG.Spec.Ct.eqContract`. Constant time: only the pointers, `a_len` and `b_len` may affect timing, not the bytes compared; only the result depends on them.
///
/// # Safety
///
/// * `a` must be valid for reads of `a_len` bytes.
/// * `b` must be valid for reads of `b_len` bytes.
/// * Neither `a` nor `b` may wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_ct_eq(a: *const u8, a_len: usize, b: *const u8, b_len: usize) -> u32 {
    core::arch::naked_asm!(
        "li %r7, 0",
        "subf %r9, %r6, %r4",
        "cmpldi %cr0, %r9, 0",
        "beq %cr0, 20f",
        "li %r3, 0",
        "b 21f",
        "20:",
        "li %r8, 0",
        "cmpldi %cr0, %r4, 0",
        "beq %cr0, 22f",
        "24:",
        "add %r10, %r3, %r8",
        "lbz %r11, 0(%r10)",
        "add %r10, %r5, %r8",
        "lbz %r12, 0(%r10)",
        "xor %r11, %r11, %r12",
        "or %r7, %r7, %r11",
        "addi %r8, %r8, 1",
        "subf %r9, %r4, %r8",
        "cmpldi %cr0, %r9, 0",
        "bne %cr0, 24b",
        "b 23f",
        "22:",
        "23:",
        "addi %r7, %r7, -1",
        "rldicl %r3, %r7, 1, 63",
        "21:",
        "blr",
    )
}
