// @generated by lean/Emit.lean. DO NOT EDIT.
//! Verified `zeroize` functions for `powerpc64le`.
#![allow(dead_code)]

/// Wipes a buffer: sets the `len` bytes at `p` to zero, and writes no other memory. A call of it is not a dead store the compiler may remove, since the compiler cannot see its code.
///
/// Contract: `VG.Spec.Zeroize.zeroizeContract`. Constant time: only `p` and `len` may affect timing, not the bytes wiped.
///
/// # Safety
///
/// * `p` must be valid for reads and writes of `len` bytes.
/// * `p` must not wrap around the end of the address space (no Rust object does).
#[unsafe(naked)]
pub(crate) unsafe extern "C" fn vg_zeroize(p: *mut u8, len: usize) {
    core::arch::naked_asm!(
        "li %r5, 0",
        "rldicl %r6, %r4, 61, 3",
        "li %r7, 7",
        "and %r4, %r4, %r7",
        "cmpldi %cr0, %r6, 0",
        "beq %cr0, 20f",
        "22:",
        "std %r5, 0(%r3)",
        "addi %r3, %r3, 8",
        "addi %r6, %r6, -1",
        "cmpldi %cr0, %r6, 0",
        "bne %cr0, 22b",
        "b 21f",
        "20:",
        "21:",
        "addi %r6, %r4, 0",
        "cmpldi %cr0, %r6, 0",
        "beq %cr0, 23f",
        "25:",
        "stb %r5, 0(%r3)",
        "addi %r3, %r3, 1",
        "addi %r6, %r6, -1",
        "cmpldi %cr0, %r6, 0",
        "bne %cr0, 25b",
        "b 24f",
        "23:",
        "24:",
        "blr",
    )
}
