import VerifiedGarbage.TCB.Artifact

/-!
# Rendering artifacts as Rust

**Trusted.** Every artifact becomes a Rust naked function whose entire body
is the printed assembly:

```rust
#[unsafe(naked)]
pub(crate) unsafe extern "<abi>" fn <name><sig> {
    core::arch::naked_asm!(
        "<line>",
        …
    )
}
```

A naked function has no compiler-generated prologue or epilogue, so the
machine code that runs is exactly the code that was verified (plus the
final `ret` from the printer). The functions of each target are collected
in `src/asm/<target>/`, one file per `module`, compiled only under the
target's `cfg`.

A call (`Code.call name body`) is a call instruction whose operand is the
symbol of the Rust function `name` (a `sym` operand). The model runs `body`
for it, so `files` checks that `name` is an artifact of the same target
whose printed code is exactly that of `body`, for every call, including the
calls in `body` itself; otherwise nothing is emitted.

The documentation of each function is its `doc`, with what its contract
requires of the memory each buffer is valid for and of where its buffers are
added to its `# Safety` section (`fullDoc`, `Sig.validDoc`, `Sig.layoutDoc`):
the latter depends on the target's calling convention and on the stack the
code uses, and both are generated from the same signature, calling
convention, `writeArgs` and `stack` as the contract (`Artifact.ofSig`), so
the `doc` must not state them itself (`checkLayout`).

An artifact whose code needs CPU features beyond the target's baseline
(`Artifact.features`) also gets a last `# Safety` item saying the CPU must
support them, and a constant of them, for the Rust that checks for them
before calling it: a `Features` set (`src/cpu.rs`), made from their names by
`Features::of`, which does not compile with a name `src/cpu.rs` does not
detect:

```rust
/// The CPU features `<name>` requires (`Artifact.features`).
pub(crate) const <NAME>_FEATURES: crate::cpu::Features = crate::cpu::Features::of(&["<feature>", …]);
```

`files` checks that `features` are exactly the features the code requires.
(The functions get no `#[target_feature]` attribute: Rust does not allow one
on naked functions. The x86 assemblers accept every instruction without it;
on AArch64 the printer's `enableFeature`/`disableFeature` directives enable
each feature for the function's body only.)
-/

namespace VG.Rust

/-- Escape a string for a Rust string literal that is also an `asm!`
template: `{`/`}` are template placeholders and must be doubled. -/
def escape (s : String) : String :=
  s.foldl (init := "") fun acc c =>
    match c with
    | '{' => acc ++ "{{"
    | '}' => acc ++ "}}"
    | '\\' => acc ++ "\\\\"
    | '"' => acc ++ "\\\""
    | '\n' => acc ++ "\\n"
    | c => acc.push c

def header : String :=
  "// @generated by lean/Emit.lean. DO NOT EDIT.\n"

def docComment (indent doc : String) : String :=
  String.join ((doc.splitOn "\n").map fun l =>
    if l.isEmpty then s!"{indent}///\n" else s!"{indent}/// {l}\n")

/-- The distinct values of `as`, in first-seen order. -/
def dedup (as : List String) : List String :=
  as.foldl (init := []) fun acc a => if acc.contains a then acc else acc ++ [a]

/-- One line of the `naked_asm!` template: a call names its function as the
operand of the same name. -/
def line (call : String) : Line → String
  | .text l => s!"        \"{escape l}\",\n"
  | .call n => s!"        \"{escape call} " ++ "{" ++ n ++ "}\",\n"

/-- `fs` as an English list of code spans: "`a`, `b` and `c`". -/
def codeList : List String → String
  | [] => ""
  | [f] => s!"`{f}`"
  | [f, g] => s!"`{f}` and `{g}`"
  | f :: fs => s!"`{f}`, " ++ codeList fs

/-- `doc`, with the CPU features `fs` added as the last item of its
`# Safety` section (which `checkFeatures` requires it to end with). -/
def featureDoc (doc : String) : List String → String
  | [] => doc
  | fs => doc ++ s!"\n* The CPU must support the {codeList fs} target \
    feature{if fs.length == 1 then "" else "s"}."

/-- The constant of the CPU features `fs` that the function `name`
requires; nothing if there are none. -/
def featuresConst (name : String) : List String → String
  | [] => ""
  | fs =>
    s!"/// The CPU features `{name}` requires (`Artifact.features`).\n" ++
    s!"pub(crate) const {name.toUpper}_FEATURES: crate::cpu::Features = \
      crate::cpu::Features::of(&[" ++
    ", ".intercalate (fs.map fun f => s!"\"{escape f}\"") ++ "]);\n\n"

/-- The features that the function `name`, with documentation `doc`, declares
(`declared`) are exactly those its code requires (`required`, with
repetitions); and if there are any, `doc` ends with its `# Safety`
section, for `featureDoc` to add them to. -/
def featureCheck (name doc : String) (required declared : List String) :
    Except String Unit := do
  let required := dedup required
  for f in required do
    unless declared.contains f do
      throw s!"{name} requires the CPU feature {f} but does not declare it"
  for f in declared do
    unless required.contains f do
      throw s!"{name} declares the CPU feature {f}, which none of its code requires"
  unless declared.isEmpty do
    match doc.splitOn "\n# " with
    | [_] => throw s!"{name} needs CPU features but its doc has no `# Safety` section"
    | parts => unless parts.getLast!.startsWith "Safety\n" do
        throw s!"{name} needs CPU features but its doc does not end with its `# Safety` section"

/-- `a` declares exactly the CPU features its code requires (`featureCheck`). -/
def checkFeatures (a : Artifact) : Except String Unit :=
  featureCheck s!"{a.target.name}: {a.name}" a.doc (a.code.requires a.target.isa.requires)
    a.features

/-- The target's printer can encode every instruction of `a`'s code, and of
the functions it calls, as the model describes it (`Printer.unencodable`). -/
def checkEncodable (a : Artifact) : Except String Unit :=
  match a.code.requires fun i => (a.target.printer.unencodable i).toList with
  | [] => pure ()
  | e :: _ => throw s!"{a.target.name}: {a.name}: {e}"

/-- `doc` with the paragraphs `notes` inserted before its `# Safety` section. -/
def insertNotes (doc : String) : List String → String
  | [] => doc
  | notes =>
    let sep := "\n\n# Safety\n\n"
    match (doc.splitOn sep).reverse with
    | safety :: rest@(_ :: _) =>
      sep.intercalate rest.reverse ++ String.join (notes.map ("\n\n" ++ ·)) ++ sep ++ safety
    | _ => doc

/-- `doc` with the items `items` first in its `# Safety` section (after
`"\n\n# Safety\n\n"`, which `checkLayout` requires it to have if there are
any), which may have no items of its own. -/
def prependSafety (doc : String) : List String → String
  | [] => doc
  | items =>
    let sep := "\n\n# Safety\n\n"
    match (doc.splitOn sep).reverse with
    | safety :: rest@(_ :: _) =>
      sep.intercalate rest.reverse ++ sep ++ "\n".intercalate (items.map ("* " ++ ·)) ++
        (if safety.isEmpty then "" else "\n" ++ safety)
    | _ => doc

/-- The documentation of `a` as emitted: its `doc`, with what its signature's
contract requires of the memory each buffer is valid for and of where its
buffers are (`Sig.layoutNote` before its `# Safety` section, `Sig.validDoc`
first in it and `Sig.layoutDoc` at the end), and the CPU features it needs
(`featureDoc`). -/
def fullDoc (a : Artifact) : String :=
  let A := a.target.abi
  let items := Sig.layoutDoc A a.sig a.writeArgs a.stack
  featureDoc (prependSafety (insertNotes a.doc (Sig.layoutNote A a.sig a.writeArgs))
    (Sig.validDoc a.sig) ++ String.join (items.map ("\n* " ++ ·))) a.features

/-- If the emitter adds anything to the documentation of `a` from its
signature (`fullDoc`), `doc` ends with its `# Safety` section, which starts
with `"\n\n# Safety\n\n"`; and `doc` does not itself state what memory a
buffer must be valid for, which the emitter generates (`Sig.validDoc`). -/
def checkLayout (a : Artifact) : Except String Unit := do
  if (a.doc.splitOn "valid for").length > 1 then
    throw s!"{a.target.name}: {a.name}'s doc states what memory a buffer must be valid for, \
      which the emitter generates from its signature (`Sig.validDoc`)"
  let A := a.target.abi
  if (Sig.layoutDoc A a.sig a.writeArgs a.stack).isEmpty &&
      (Sig.layoutNote A a.sig a.writeArgs).isEmpty && (Sig.validDoc a.sig).isEmpty then return
  let ok := match a.doc.splitOn "\n# " with
    | [_] => false
    | parts => parts.getLast!.startsWith "Safety\n" &&
        (a.doc.splitOn "\n\n# Safety\n\n").length > 1
  unless ok do
    throw s!"{a.target.name}: {a.name} has buffers but its doc does not end with its \
      `# Safety` section"

/-- One artifact as a Rust naked function; `moduleOf` gives the module of
each function it calls. The printer's `funcAlign` comes last, after the
return (`Printer.function`) and any directives that follow it. -/
def function (a : Artifact) (moduleOf : String → String) : String :=
  let P := a.target.printer
  let body := (a.features.flatMap P.enableFeature).map .text ++ P.function a.code ++
    (a.features.flatMap P.disableFeature).map .text ++ P.funcAlign.map .text
  let callees := dedup (body.filterMap fun | .call n => some n | .text _ => none)
  featuresConst a.name a.features ++
  docComment "" (fullDoc a) ++
  "#[unsafe(naked)]\n" ++
  s!"pub(crate) unsafe extern \"{a.target.rustAbi}\" fn {a.name}{a.sig.rust} " ++ "{\n" ++
  "    core::arch::naked_asm!(\n" ++
  String.join (body.map (line a.target.printer.call)) ++
  String.join (callees.map fun n => s!"        {n} = sym super::{moduleOf n}::{n},\n") ++
  "    )\n" ++
  "}\n"

/-- The distinct values of `f` over `as`, in first-seen order. -/
def distinct (as : List Artifact) (f : Artifact → String) : List String :=
  dedup (as.map f)

/-- The artifact that a call of `name` in `a` calls. -/
def callee (as : List Artifact) (a : Artifact) (name : String) : Option Artifact :=
  as.find? fun b => b.target.name == a.target.name && b.name == name

/-- The first of `calls` (`Code.calls`: the name of each function called and
the code the model runs for it) that is not of a function `printed` gives the
printed code of (`some (n, false)`), or whose code `P` does not print as that
(`some (n, true)`); `none` if every call is of the code it runs.

A function can be called hundreds of times in one artifact's `calls`, so
only the first call of each name is printed and compared with `printed`;
every later one is compared with the first one's code, by equal printed
code, which `withPtrEq` returns at once if the two are the same value in
memory, as they usually are. -/
def badCall {M : ISA} (P : Printer M) (printed : String → Option (List Line))
    (calls : List (String × Prog M)) : Option (String × Bool) := Id.run do
  -- The first call of each function checked so far, with its code.
  let mut first : List (String × Prog M) := []
  for (n, body) in calls do
    match first.find? (·.1 == n) with
    | some (_, body₀) =>
      unless withPtrEq body body₀ (fun _ => P.function body == P.function body₀)
          (fun h => by simp [h]) do
        return some (n, true)
    | none =>
      match printed n with
      | none => return some (n, false)
      | some lines =>
        unless P.function body == lines do return some (n, true)
        first := (n, body) :: first
  return none

/-- Every call in the code of `a`, and in the code of the functions it calls,
is of an artifact of the same target whose printed code is that of the
called code (`badCall`). -/
def checkCalls (as : List Artifact) (a : Artifact) : Except String Unit :=
  match badCall a.target.printer
      (fun n => (callee as a n).map fun b => b.target.printer.function b.code) a.code.calls with
  | none => pure ()
  | some (n, false) => throw s!"{a.target.name}: {a.name} calls {n}, which is not an artifact"
  | some (n, true) =>
    throw s!"{a.target.name}: {a.name} calls {n}, whose code is not what the call runs"

/-- The artifact carries the contract of the `Api` it is made from
(`Artifact.contracts`), which it is proven against (`Artifact.ofApi`): so its
name, signature and documentation are those `Spec/` gives that contract. -/
def checkApi (a : Artifact) : Except String Unit :=
  unless a.contracts.isSome do
    throw s!"{a.target.name}: {a.name} is not made from an `Api` with a contract \
      (`Api.contracts`)"

/-- No two artifacts of a target have the same name. -/
def checkUnique (as : List Artifact) : Except String Unit :=
  as.forM fun a =>
    unless (as.filter fun b => b.target.name == a.target.name && b.name == a.name).length == 1 do
      throw s!"{a.target.name}: {a.name} is defined more than once"

/-- `mod` declarations for generated child modules (never reformatted by rustfmt). -/
def modDecls (ms : List String) (cfg : String → Option String) : String :=
  String.join (ms.map fun m =>
    let c := match cfg m with
      | some c => s!"#[cfg({c})]\n"
      | none => ""
    s!"\n{c}#[rustfmt::skip]\npub(crate) mod {m};\n")

/-- The generated files, given the module of each function each artifact calls. -/
def render (as : List Artifact) (moduleOf : Artifact → String → String) : List (String × String) :=
  let targets := distinct as (·.target.name)
  let cfgOf (t : String) : Option String := (as.find? (·.target.name == t)).map (·.target.rustCfg)
  let root :=
    header ++
    "//! Formally verified assembly, emitted from Lean. See `lean/README.md`.\n" ++
    "//!\n" ++
    "//! Every function in these modules is the direct rendering of an `Artifact`\n" ++
    "//! whose machine code has been proven correct, memory safe and constant time\n" ++
    "//! against its contract.\n" ++
    modDecls targets cfgOf
  let perTarget (t : String) : List (String × String) :=
    let arts := as.filter (·.target.name == t)
    -- In order of their names, wherever their artifacts come in the list.
    let modules := (distinct arts (·.module)).mergeSort (· ≤ ·)
    (s!"{t}/mod.rs", header ++ s!"//! Verified functions for `{t}`.\n" ++
      modDecls modules (fun _ => none)) ::
    modules.map fun m =>
      (s!"{t}/{m}.rs",
        header ++ s!"//! Verified `{m}` functions for `{t}`.\n" ++
        "#![allow(dead_code)]\n" ++
        String.join ((arts.filter (·.module == m)).map fun a => "\n" ++ function a (moduleOf a)))
  ("mod.rs", root) :: (targets.map perTarget).flatten

/-- The generated files, as paths relative to `src/asm/` and their contents:
`mod.rs`, and for each target `<target>/mod.rs` and one `<target>/<module>.rs`
per module; an error if an artifact is not made from an `Api` with a
contract (`checkApi`), two artifacts of a target have the same name
(`checkUnique`), a call is not of the code it runs (`checkCalls`), an
artifact's features are not those its code requires (`checkFeatures`), its
code has an instruction its target's printer cannot encode
(`checkEncodable`) or its doc has no `# Safety` section at its end for what
`fullDoc` adds to it (`checkLayout`). -/
def files (as : List Artifact) : Except String (List (String × String)) := do
  as.forM checkApi
  checkUnique as
  as.forM (checkCalls as)
  as.forM checkFeatures
  as.forM checkEncodable
  as.forM checkLayout
  return render as fun a n => ((callee as a n).map (·.module)).getD ""

end VG.Rust
